  // ── Lessons 501–750 additions ──────────────────────────────
  万: { meaning: "ten thousand; myriad", onyomi: ["マン", "バン"], kunyomi: ["よろず"] },
  与: { meaning: "give; participate in", onyomi: ["ヨ"], kunyomi: ["あた・える"] },
  並: { meaning: "row; line up; ordinary", onyomi: ["ヘイ"], kunyomi: ["なみ", "なら・ぶ", "なら・べる"] },
  主: { meaning: "main; lord; master", onyomi: ["シュ", "ス"], kunyomi: ["おも", "ぬし"] },
  久: { meaning: "long time; old", onyomi: ["キュウ"], kunyomi: ["ひさ・しい"] },
  了: { meaning: "complete; finish", onyomi: ["リョウ"] },
  互: { meaning: "mutual; each other", onyomi: ["ゴ"], kunyomi: ["たが・い"] },
  企: { meaning: "plan; undertake", onyomi: ["キ"], kunyomi: ["たくら・む"] },
  伴: { meaning: "accompany; companion", onyomi: ["バン", "ハン"], kunyomi: ["ともな・う"] },
  低: { meaning: "low", onyomi: ["テイ"], kunyomi: ["ひく・い", "ひく・める"] },
  促: { meaning: "urge; promote", onyomi: ["ソク"], kunyomi: ["うなが・す"] },
  候: { meaning: "climate; season; sign", onyomi: ["コウ"], kunyomi: ["そうろう"] },
  傷: { meaning: "wound; injury; hurt", onyomi: ["ショウ"], kunyomi: ["きず", "いた・む", "きずつ・く"] },
  傾: { meaning: "lean; incline; tendency", onyomi: ["ケイ"], kunyomi: ["かたむ・く", "かたむ・ける"] },
  刑: { meaning: "punishment; penalty", onyomi: ["ケイ"] },
  到: { meaning: "arrive; reach", onyomi: ["トウ"] },
  制: { meaning: "system; control; regulation", onyomi: ["セイ"] },
  削: { meaning: "cut off; sharpen; reduce", onyomi: ["サク"], kunyomi: ["けず・る"] },
  功: { meaning: "achievement; merit", onyomi: ["コウ", "ク"] },
  劣: { meaning: "inferior; be worse", onyomi: ["レツ"], kunyomi: ["おと・る"] },
  占: { meaning: "occupy; fortune-telling", onyomi: ["セン"], kunyomi: ["し・める", "うらな・う"] },
  双: { meaning: "pair; both; two", onyomi: ["ソウ"], kunyomi: ["ふた"] },
  周: { meaning: "circumference; surroundings", onyomi: ["シュウ"], kunyomi: ["まわ・り"] },
  善: { meaning: "good; goodness; virtue", onyomi: ["ゼン"], kunyomi: ["よ・い"] },
  型: { meaning: "model; type; pattern", onyomi: ["ケイ"], kunyomi: ["かた"] },
  基: { meaning: "basis; foundation", onyomi: ["キ"], kunyomi: ["もと", "もと・づく"] },
  塩: { meaning: "salt", onyomi: ["エン"], kunyomi: ["しお"] },
  妥: { meaning: "amicable; compromise", onyomi: ["タ"] },
  威: { meaning: "authority; dignity; threaten", onyomi: ["イ"] },
  寸: { meaning: "measurement; a little", onyomi: ["スン"] },
  尊: { meaning: "revere; respect; precious", onyomi: ["ソン"], kunyomi: ["たっと・い", "とうと・ぶ"] },
  山: { meaning: "mountain", onyomi: ["サン"], kunyomi: ["やま"] },
  島: { meaning: "island", onyomi: ["トウ"], kunyomi: ["しま"] },
  川: { meaning: "river", onyomi: ["セン"], kunyomi: ["かわ"] },
  府: { meaning: "urban prefecture; government office", onyomi: ["フ"] },
  弾: { meaning: "bullet; play (instrument); flick", onyomi: ["ダン"], kunyomi: ["ひ・く", "たま", "はじ・く"] },
  律: { meaning: "law; rhythm", onyomi: ["リツ", "リチ"] },
  慎: { meaning: "discreet; careful", onyomi: ["シン"], kunyomi: ["つつし・む"] },
  戦: { meaning: "war; battle; match", onyomi: ["セン"], kunyomi: ["たたか・う"] },
  承: { meaning: "consent; hear; receive", onyomi: ["ショウ"], kunyomi: ["うけたまわ・る"] },
  拠: { meaning: "based on; foundation", onyomi: ["キョ", "コ"] },
  拡: { meaning: "expand; broaden", onyomi: ["カク"] },
  挑: { meaning: "challenge; provoke", onyomi: ["チョウ"], kunyomi: ["いど・む"] },
  捗: { meaning: "progress", onyomi: ["チョク", "チョウ"] },
  捜: { meaning: "search; look for", onyomi: ["ソウ"], kunyomi: ["さが・す"] },
  推: { meaning: "infer; guess; recommend", onyomi: ["スイ"], kunyomi: ["お・す"] },
  摘: { meaning: "pick; pluck; expose", onyomi: ["テキ"], kunyomi: ["つ・む"] },
  撃: { meaning: "attack; shoot", onyomi: ["ゲキ"], kunyomi: ["う・つ"] },
  攻: { meaning: "attack; besiege", onyomi: ["コウ"], kunyomi: ["せ・める"] },
  政: { meaning: "government; politics", onyomi: ["セイ", "ショウ"], kunyomi: ["まつりごと"] },
  旧: { meaning: "old; former", onyomi: ["キュウ"] },
  昨: { meaning: "previous; last", onyomi: ["サク"] },
  景: { meaning: "scenery; view; condition", onyomi: ["ケイ"] },
  暗: { meaning: "dark; gloomy; memorize", onyomi: ["アン"], kunyomi: ["くら・い"] },
  曲: { meaning: "bend; curve; melody", onyomi: ["キョク"], kunyomi: ["ま・げる", "ま・がる"] },
  析: { meaning: "analyze; divide", onyomi: ["セキ"] },
  林: { meaning: "woods; forest", onyomi: ["リン"], kunyomi: ["はやし"] },
  染: { meaning: "dye; be infected; stain", onyomi: ["セン"], kunyomi: ["そ・める", "し・みる", "し・み"] },
  森: { meaning: "forest; woods", onyomi: ["シン"], kunyomi: ["もり"] },
  概: { meaning: "outline; approximately", onyomi: ["ガイ"] },
  比: { meaning: "compare; ratio", onyomi: ["ヒ"], kunyomi: ["くら・べる"] },
  氾: { meaning: "overflow; flood", onyomi: ["ハン"] },
  洪: { meaning: "flood; vast", onyomi: ["コウ"] },
  浸: { meaning: "soak; immerse", onyomi: ["シン"], kunyomi: ["ひた・す", "つ・かる"] },
  濫: { meaning: "overflow; excessive", onyomi: ["ラン"] },
  炭: { meaning: "charcoal; coal", onyomi: ["タン"], kunyomi: ["すみ"] },
  為: { meaning: "reason; because; for the sake of", onyomi: ["イ"], kunyomi: ["ため"] },
  照: { meaning: "shine; illuminate; compare", onyomi: ["ショウ"], kunyomi: ["て・る", "て・らす"] },
  男: { meaning: "man; male", onyomi: ["ダン", "ナン"], kunyomi: ["おとこ"] },
  異: { meaning: "different; strange", onyomi: ["イ"], kunyomi: ["こと"] },
  疑: { meaning: "doubt; suspect", onyomi: ["ギ"], kunyomi: ["うたが・う"] },
  益: { meaning: "profit; benefit", onyomi: ["エキ", "ヤク"] },
  監: { meaning: "supervise; observe", onyomi: ["カン"] },
  禁: { meaning: "prohibit; ban", onyomi: ["キン"] },
  秀: { meaning: "excel; excellent", onyomi: ["シュウ"], kunyomi: ["ひい・でる"] },
  私: { meaning: "private; I; me", onyomi: ["シ"], kunyomi: ["わたし", "わたくし"] },
  程: { meaning: "extent; degree; rule", onyomi: ["テイ"], kunyomi: ["ほど"] },
  穏: { meaning: "calm; peaceful", onyomi: ["オン"], kunyomi: ["おだ・やか"] },
  突: { meaning: "thrust; sudden; poke", onyomi: ["トツ"], kunyomi: ["つ・く"] },
  章: { meaning: "chapter; badge; writing", onyomi: ["ショウ"] },
  競: { meaning: "compete; race", onyomi: ["キョウ", "ケイ"], kunyomi: ["きそ・う", "せ・る"] },
  精: { meaning: "spirit; energy; refined", onyomi: ["セイ", "ショウ"] },
  系: { meaning: "lineage; system", onyomi: ["ケイ"] },
  紋: { meaning: "crest; pattern; grain", onyomi: ["モン"] },
  繰: { meaning: "reel; spin; do repeatedly", onyomi: ["ソウ"], kunyomi: ["く・る"] },
  翌: { meaning: "the following (day/year)", onyomi: ["ヨク"] },
  耐: { meaning: "endure; withstand", onyomi: ["タイ"], kunyomi: ["た・える"] },
  肌: { meaning: "skin; body", kunyomi: ["はだ"] },
  胆: { meaning: "gallbladder; courage", onyomi: ["タン"] },
  背: { meaning: "back; height; disobey", onyomi: ["ハイ"], kunyomi: ["せ", "せい", "そむ・く"] },
  脅: { meaning: "threaten; menace", onyomi: ["キョウ"], kunyomi: ["おびや・かす", "おど・す"] },
  脆: { meaning: "fragile; brittle", onyomi: ["ゼイ"], kunyomi: ["もろ・い"] },
  若: { meaning: "young; if", onyomi: ["ジャク", "ニャク"], kunyomi: ["わか・い", "も・し"] },
  茶: { meaning: "tea", onyomi: ["チャ", "サ"] },
  衝: { meaning: "collide; impulse", onyomi: ["ショウ"] },
  裏: { meaning: "back; reverse side; inside", onyomi: ["リ"], kunyomi: ["うら"] },
  覆: { meaning: "cover; overturn", onyomi: ["フク"], kunyomi: ["おお・う", "くつがえ・す"] },
  訂: { meaning: "correct; revise", onyomi: ["テイ"] },
  詳: { meaning: "detailed; know well", onyomi: ["ショウ"], kunyomi: ["くわ・しい"] },
  誰: { meaning: "who", kunyomi: ["だれ"] },
  論: { meaning: "argument; theory; discuss", onyomi: ["ロン"] },
  謙: { meaning: "humble; modest", onyomi: ["ケン"] },
  象: { meaning: "elephant; image; shape", onyomi: ["ゾウ", "ショウ"] },
  財: { meaning: "wealth; property", onyomi: ["ザイ", "サイ"] },
  責: { meaning: "duty; blame; censure", onyomi: ["セキ"], kunyomi: ["せ・める"] },
  賑: { meaning: "bustling; lively", kunyomi: ["にぎ・わう", "にぎ・やか"] },
  賛: { meaning: "praise; approve", onyomi: ["サン"] },
  較: { meaning: "compare", onyomi: ["カク"] },
  輸: { meaning: "transport; send", onyomi: ["ユ"] },
  迎: { meaning: "welcome; greet", onyomi: ["ゲイ"], kunyomi: ["むか・える"] },
  透: { meaning: "transparent; permeate", onyomi: ["トウ"], kunyomi: ["す・く", "す・ける", "とお・る"] },
  途: { meaning: "route; way; path", onyomi: ["ト"] },
  逮: { meaning: "arrest; capture", onyomi: ["タイ"] },
  逸: { meaning: "deviate; escape; excel", onyomi: ["イツ"], kunyomi: ["そ・れる"] },
  遂: { meaning: "accomplish; carry out", onyomi: ["スイ"], kunyomi: ["と・げる"] },
  遇: { meaning: "treatment; encounter", onyomi: ["グウ"] },
  遜: { meaning: "modest; humble", onyomi: ["ソン"] },
  酒: { meaning: "alcohol; sake", onyomi: ["シュ"], kunyomi: ["さけ", "さか"] },
  針: { meaning: "needle; pointer; policy", onyomi: ["シン"], kunyomi: ["はり"] },
  閉: { meaning: "close; shut", onyomi: ["ヘイ"], kunyomi: ["し・める", "と・じる", "し・まる"] },
  陥: { meaning: "fall into; cave in; capture", onyomi: ["カン"], kunyomi: ["おちい・る", "おとしい・れる"] },
  隊: { meaning: "squad; unit; regiment", onyomi: ["タイ"] },
  雇: { meaning: "employ; hire", onyomi: ["コ"], kunyomi: ["やと・う"] },
  雪: { meaning: "snow", onyomi: ["セツ"], kunyomi: ["ゆき"] },
  需: { meaning: "demand; need", onyomi: ["ジュ"] },
  項: { meaning: "item; clause; term", onyomi: ["コウ"] },
  飲: { meaning: "drink", onyomi: ["イン"], kunyomi: ["の・む"] },
