  {
    id: "lesson-51",
    title: "JLPT N2 Advanced Weather & Climate Vocabulary #51",
    subtitle: "Weather • Climate",
    youtubeTitle: "JLPT N2 Daily Life Vocabulary #51 | Advanced Weather & Climate",
    category: "Daily Life",
    subcategories: ["Weather", "Climate"],
    vocabularyIds: idRange(4501),
  },
  {
    id: "lesson-52",
    title: "JLPT N2 Social Etiquette & Consideration Vocabulary #52",
    subtitle: "Etiquette • Consideration",
    youtubeTitle: "JLPT N2 Daily Life Vocabulary #52 | Social Etiquette & Consideration",
    category: "Daily Life",
    subcategories: ["Etiquette", "Consideration"],
    vocabularyIds: idRange(4511),
  },
  {
    id: "lesson-53",
    title: "JLPT N2 Workplace Communication Vocabulary #53",
    subtitle: "Workplace • Communication",
    youtubeTitle: "JLPT N2 Daily Life Vocabulary #53 | Workplace Communication",
    category: "Daily Life",
    subcategories: ["Workplace", "Communication"],
    vocabularyIds: idRange(4521),
  },
  {
    id: "lesson-54",
    title: "JLPT N2 Decisions & Problem Solving Vocabulary #54",
    subtitle: "Decisions • Problem Solving",
    youtubeTitle: "JLPT N2 Daily Life Vocabulary #54 | Decisions & Problem Solving",
    category: "Daily Life",
    subcategories: ["Decisions", "Problem Solving"],
    vocabularyIds: idRange(4531),
  },
  {
    id: "lesson-55",
    title: "JLPT N2 Quality & Manufacturing Vocabulary #55",
    subtitle: "Quality • Manufacturing",
    youtubeTitle: "JLPT N2 Daily Life Vocabulary #55 | Quality & Manufacturing",
    category: "Daily Life",
    subcategories: ["Quality", "Manufacturing"],
    vocabularyIds: idRange(4541),
  },
  {
    id: "lesson-56",
    title: "JLPT N2 Research & Data Vocabulary #56",
    subtitle: "Research • Data",
    youtubeTitle: "JLPT N2 Daily Life Vocabulary #56 | Research & Data",
    category: "Daily Life",
    subcategories: ["Research", "Data"],
    vocabularyIds: idRange(4551),
  },
  {
    id: "lesson-57",
    title: "JLPT N2 Opinions & Arguments Vocabulary #57",
    subtitle: "Opinions • Arguments",
    youtubeTitle: "JLPT N2 Daily Life Vocabulary #57 | Opinions & Arguments",
    category: "Daily Life",
    subcategories: ["Opinions", "Arguments"],
    vocabularyIds: idRange(4561),
  },
  {
    id: "lesson-58",
    title: "JLPT N2 Personality & Character Vocabulary #58",
    subtitle: "Personality • Character",
    youtubeTitle: "JLPT N2 Daily Life Vocabulary #58 | Personality & Character",
    category: "Daily Life",
    subcategories: ["Personality", "Character"],
    vocabularyIds: idRange(4571),
  },
  {
    id: "lesson-59",
    title: "JLPT N2 Conflict & Relationships Vocabulary #59",
    subtitle: "Conflict • Relationships",
    youtubeTitle: "JLPT N2 Daily Life Vocabulary #59 | Conflict & Relationships",
    category: "Daily Life",
    subcategories: ["Conflict", "Relationships"],
    vocabularyIds: idRange(4581),
  },
  {
    id: "lesson-60",
    title: "JLPT N2 Rules & Compliance Vocabulary #60",
    subtitle: "Rules • Compliance",
    youtubeTitle: "JLPT N2 Daily Life Vocabulary #60 | Rules & Compliance",
    category: "Daily Life",
    subcategories: ["Rules", "Compliance"],
    vocabularyIds: idRange(4591),
  },
  {
    id: "lesson-61",
    title: "JLPT N2 Government & Politics Vocabulary #61",
    subtitle: "Government • Politics",
    youtubeTitle: "JLPT N2 Daily Life Vocabulary #61 | Government & Politics",
    category: "Daily Life",
    subcategories: ["Government", "Politics"],
    vocabularyIds: idRange(4601),
  },
  {
    id: "lesson-62",
    title: "JLPT N2 Economy & Business Conditions Vocabulary #62",
    subtitle: "Economy • Business",
    youtubeTitle: "JLPT N2 Daily Life Vocabulary #62 | Economy & Business Conditions",
    category: "Daily Life",
    subcategories: ["Economy", "Business"],
    vocabularyIds: idRange(4611),
  },
  {
    id: "lesson-63",
    title: "JLPT N2 Employment Conditions Vocabulary #63",
    subtitle: "Employment • Labor",
    youtubeTitle: "JLPT N2 Daily Life Vocabulary #63 | Employment Conditions",
    category: "Daily Life",
    subcategories: ["Employment", "Labor"],
    vocabularyIds: idRange(4621),
  },
  {
    id: "lesson-64",
    title: "JLPT N2 Environment & Sustainability Vocabulary #64",
    subtitle: "Environment • Sustainability",
    youtubeTitle: "JLPT N2 Daily Life Vocabulary #64 | Environment & Sustainability",
    category: "Daily Life",
    subcategories: ["Environment", "Sustainability"],
    vocabularyIds: idRange(4631),
  },
  {
    id: "lesson-65",
    title: "JLPT N2 Crime & Public Safety Vocabulary #65",
    subtitle: "Crime • Public Safety",
    youtubeTitle: "JLPT N2 Daily Life Vocabulary #65 | Crime & Public Safety",
    category: "Daily Life",
    subcategories: ["Crime", "Public Safety"],
    vocabularyIds: idRange(4641),
  },
  {
    id: "lesson-66",
    title: "JLPT N2 Accidents & Insurance Vocabulary #66",
    subtitle: "Accidents • Insurance",
    youtubeTitle: "JLPT N2 Daily Life Vocabulary #66 | Accidents & Insurance",
    category: "Daily Life",
    subcategories: ["Accidents", "Insurance"],
    vocabularyIds: idRange(4651),
  },
  {
    id: "lesson-67",
    title: "JLPT N2 News & Public Information Vocabulary #67",
    subtitle: "News • Media",
    youtubeTitle: "JLPT N2 Daily Life Vocabulary #67 | News & Public Information",
    category: "Daily Life",
    subcategories: ["News", "Media"],
    vocabularyIds: idRange(4661),
  },
  {
    id: "lesson-68",
    title: "JLPT N2 Digital Security & Privacy Vocabulary #68",
    subtitle: "Digital Security • Privacy",
    youtubeTitle: "JLPT N2 Daily Life Vocabulary #68 | Digital Security & Privacy",
    category: "Daily Life",
    subcategories: ["Digital Security", "Privacy"],
    vocabularyIds: idRange(4671),
  },
  {
    id: "lesson-69",
    title: "JLPT N2 Science & Technology Vocabulary #69",
    subtitle: "Science • Technology",
    youtubeTitle: "JLPT N2 Daily Life Vocabulary #69 | Science & Technology",
    category: "Daily Life",
    subcategories: ["Science", "Technology"],
    vocabularyIds: idRange(4681),
  },
  {
    id: "lesson-70",
    title: "JLPT N2 Changes & Trends Vocabulary #70",
    subtitle: "Changes • Trends",
    youtubeTitle: "JLPT N2 Daily Life Vocabulary #70 | Changes & Trends",
    category: "Daily Life",
    subcategories: ["Changes", "Trends"],
    vocabularyIds: idRange(4691),
  },
  {
    id: "lesson-71",
    title: "JLPT N2 Causes & Consequences Vocabulary #71",
    subtitle: "Causes • Consequences",
    youtubeTitle: "JLPT N2 Daily Life Vocabulary #71 | Causes & Consequences",
    category: "Daily Life",
    subcategories: ["Causes", "Consequences"],
    vocabularyIds: idRange(4701),
  },
  {
    id: "lesson-72",
    title: "JLPT N2 Possibility & Prediction Vocabulary #72",
    subtitle: "Possibility • Prediction",
    youtubeTitle: "JLPT N2 Daily Life Vocabulary #72 | Possibility & Prediction",
    category: "Daily Life",
    subcategories: ["Possibility", "Prediction"],
    vocabularyIds: idRange(4711),
  },
  {
    id: "lesson-73",
    title: "JLPT N2 Evaluation & Comparison Vocabulary #73",
    subtitle: "Evaluation • Comparison",
    youtubeTitle: "JLPT N2 Daily Life Vocabulary #73 | Evaluation & Comparison",
    category: "Daily Life",
    subcategories: ["Evaluation", "Comparison"],
    vocabularyIds: idRange(4721),
  },
  {
    id: "lesson-74",
    title: "JLPT N2 Academic Reading Vocabulary Vocabulary #74",
    subtitle: "Academic • Reading",
    youtubeTitle: "JLPT N2 Daily Life Vocabulary #74 | Academic Reading Vocabulary",
    category: "Daily Life",
    subcategories: ["Academic", "Reading"],
    vocabularyIds: idRange(4731),
  },
  {
    id: "lesson-75",
    title: "JLPT N2 Abstract High-Frequency N2 Verbs Vocabulary #75",
    subtitle: "Abstract • Verbs",
    youtubeTitle: "JLPT N2 Daily Life Vocabulary #75 | Abstract High-Frequency N2 Verbs",
    category: "Daily Life",
    subcategories: ["Abstract", "Verbs"],
    vocabularyIds: idRange(4741),
  },
