  // ── Lesson 551–560 · Research & Data ───────────────
  {
    id: 4551,
    subcategory: "Research & Data",
    folder: "research-data",
    word: "調査",
    reading: "ちょうさ",
    meaning: "investigation; survey",
    phrase: "調査を行う",
    phraseReading: "ちょうさ を おこなう",
    phraseMeaning: "to conduct a survey",
    sentence: "市場調査の結果をまとめた。",
    sentenceReading: "しじょう ちょうさ の けっか を まとめた。",
    sentenceMeaning: "I compiled the results of the market survey.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4552,
    subcategory: "Research & Data",
    folder: "research-data",
    word: "分析",
    reading: "ぶんせき",
    meaning: "analysis",
    phrase: "データを分析する",
    phraseReading: "でーた を ぶんせき する",
    phraseMeaning: "to analyze data",
    sentence: "専門家がアンケートの結果を分析した。",
    sentenceReading: "せんもんか が あんけーと の けっか を ぶんせき した。",
    sentenceMeaning: "An expert analyzed the results of the questionnaire.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4553,
    subcategory: "Research & Data",
    folder: "research-data",
    word: "統計",
    reading: "とうけい",
    meaning: "statistics",
    phrase: "統計を取る",
    phraseReading: "とうけい を とる",
    phraseMeaning: "to compile statistics",
    sentence: "人口統計によると若者が減っている。",
    sentenceReading: "じんこう とうけい に よると わかもの が へって いる。",
    sentenceMeaning: "According to population statistics, the number of young people is decreasing.",
    wordType: "noun",
  },
  {
    id: 4554,
    subcategory: "Research & Data",
    folder: "research-data",
    word: "傾向",
    reading: "けいこう",
    meaning: "tendency; trend",
    phrase: "増加傾向にある",
    phraseReading: "ぞうか けいこう に ある",
    phraseMeaning: "to be on an increasing trend",
    sentence: "最近、消費は減少傾向にある。",
    sentenceReading: "さいきん、しょうひ は げんしょう けいこう に ある。",
    sentenceMeaning: "Recently, consumption has been on a decreasing trend.",
    wordType: "noun",
  },
  {
    id: 4555,
    subcategory: "Research & Data",
    folder: "research-data",
    word: "仮説",
    reading: "かせつ",
    meaning: "hypothesis",
    phrase: "仮説を立てる",
    phraseReading: "かせつ を たてる",
    phraseMeaning: "to formulate a hypothesis",
    sentence: "研究者は新しい仮説を立てて実験を行った。",
    sentenceReading: "けんきゅうしゃ は あたらしい かせつ を たてて じっけん を おこなった。",
    sentenceMeaning: "The researcher formulated a new hypothesis and conducted an experiment.",
    wordType: "noun",
  },
  {
    id: 4556,
    subcategory: "Research & Data",
    folder: "research-data",
    word: "根拠",
    reading: "こんきょ",
    meaning: "basis; grounds",
    phrase: "根拠を示す",
    phraseReading: "こんきょ を しめす",
    phraseMeaning: "to show grounds for something",
    sentence: "彼の話には根拠がない。",
    sentenceReading: "かれ の はなし に は こんきょ が ない。",
    sentenceMeaning: "There is no basis for what he says.",
    wordType: "noun",
  },
  {
    id: 4557,
    subcategory: "Research & Data",
    folder: "research-data",
    word: "検証",
    reading: "けんしょう",
    meaning: "verification",
    phrase: "効果を検証する",
    phraseReading: "こうか を けんしょう する",
    phraseMeaning: "to verify the effect",
    sentence: "新しい方法の効果を検証するため実験を行った。",
    sentenceReading: "あたらしい ほうほう の こうか を けんしょう する ため じっけん を おこなった。",
    sentenceMeaning: "We conducted an experiment to verify the effect of the new method.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4558,
    subcategory: "Research & Data",
    folder: "research-data",
    word: "対象",
    reading: "たいしょう",
    meaning: "target; subject",
    phrase: "調査の対象",
    phraseReading: "ちょうさ の たいしょう",
    phraseMeaning: "the subject of a survey",
    sentence: "このアンケートは二十代を対象としている。",
    sentenceReading: "この あんけーと は にじゅうだい を たいしょう と して いる。",
    sentenceMeaning: "This questionnaire targets people in their twenties.",
    wordType: "noun",
  },
  {
    id: 4559,
    subcategory: "Research & Data",
    folder: "research-data",
    word: "数値",
    reading: "すうち",
    meaning: "numerical value",
    phrase: "数値を示す",
    phraseReading: "すうち を しめす",
    phraseMeaning: "to show a numerical value",
    sentence: "グラフには詳しい数値が示されている。",
    sentenceReading: "ぐらふ に は くわしい すうち が しめされて いる。",
    sentenceMeaning: "Detailed numerical values are shown in the graph.",
    wordType: "noun",
  },
  {
    id: 4560,
    subcategory: "Research & Data",
    folder: "research-data",
    word: "比率",
    reading: "ひりつ",
    meaning: "ratio",
    phrase: "男女の比率",
    phraseReading: "だんじょ の ひりつ",
    phraseMeaning: "the ratio of men to women",
    sentence: "この学校は男女の比率がほぼ同じだ。",
    sentenceReading: "この がっこう は だんじょ の ひりつ が ほぼ おなじ だ。",
    sentenceMeaning: "The ratio of men to women at this school is almost equal.",
    wordType: "noun",
  },

  // ── Lesson 561–570 · Opinions & Arguments ───────────────
  {
    id: 4561,
    subcategory: "Opinions & Arguments",
    folder: "opinions-arguments",
    word: "主張",
    reading: "しゅちょう",
    meaning: "assertion; argument",
    phrase: "自分の考えを主張する",
    phraseReading: "じぶん の かんがえ を しゅちょう する",
    phraseMeaning: "to assert one's own idea",
    sentence: "彼は最後まで自分の主張を変えなかった。",
    sentenceReading: "かれ は さいご まで じぶん の しゅちょう を かえなかった。",
    sentenceMeaning: "He did not change his assertion until the very end.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4562,
    subcategory: "Opinions & Arguments",
    folder: "opinions-arguments",
    word: "意見",
    reading: "いけん",
    meaning: "opinion",
    phrase: "意見を述べる",
    phraseReading: "いけん を のべる",
    phraseMeaning: "to state one's opinion",
    sentence: "会議で自分の意見を述べた。",
    sentenceReading: "かいぎ で じぶん の いけん を のべた。",
    sentenceMeaning: "I stated my opinion at the meeting.",
    wordType: "noun",
  },
  {
    id: 4563,
    subcategory: "Opinions & Arguments",
    folder: "opinions-arguments",
    word: "見解",
    reading: "けんかい",
    meaning: "view; opinion",
    phrase: "見解を示す",
    phraseReading: "けんかい を しめす",
    phraseMeaning: "to show one's view",
    sentence: "専門家たちの見解は分かれている。",
    sentenceReading: "せんもんか たち の けんかい は わかれて いる。",
    sentenceMeaning: "The experts' views are divided.",
    wordType: "noun",
  },
  {
    id: 4564,
    subcategory: "Opinions & Arguments",
    folder: "opinions-arguments",
    word: "賛成",
    reading: "さんせい",
    meaning: "agreement; support",
    phrase: "計画に賛成する",
    phraseReading: "けいかく に さんせい する",
    phraseMeaning: "to agree with a plan",
    sentence: "多くの人がその提案に賛成した。",
    sentenceReading: "おおく の ひと が その ていあん に さんせい した。",
    sentenceMeaning: "Many people agreed with the proposal.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4565,
    subcategory: "Opinions & Arguments",
    folder: "opinions-arguments",
    word: "反対",
    reading: "はんたい",
    meaning: "opposition",
    phrase: "計画に反対する",
    phraseReading: "けいかく に はんたい する",
    phraseMeaning: "to oppose a plan",
    sentence: "両親は私の留学に反対している。",
    sentenceReading: "りょうしん は わたし の りゅうがく に はんたい して いる。",
    sentenceMeaning: "My parents are opposed to my studying abroad.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4566,
    subcategory: "Opinions & Arguments",
    folder: "opinions-arguments",
    word: "批判",
    reading: "ひはん",
    meaning: "criticism",
    phrase: "政府を批判する",
    phraseReading: "せいふ を ひはん する",
    phraseMeaning: "to criticize the government",
    sentence: "新しい政策は多くの批判を受けた。",
    sentenceReading: "あたらしい せいさく は おおく の ひはん を うけた。",
    sentenceMeaning: "The new policy received a lot of criticism.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4567,
    subcategory: "Opinions & Arguments",
    folder: "opinions-arguments",
    word: "反論",
    reading: "はんろん",
    meaning: "counterargument",
    phrase: "反論を述べる",
    phraseReading: "はんろん を のべる",
    phraseMeaning: "to state a counterargument",
    sentence: "彼女は上司の意見に反論した。",
    sentenceReading: "かのじょ は じょうし の いけん に はんろん した。",
    sentenceMeaning: "She raised a counterargument against her boss's opinion.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4568,
    subcategory: "Opinions & Arguments",
    folder: "opinions-arguments",
    word: "指摘",
    reading: "してき",
    meaning: "pointing out",
    phrase: "問題点を指摘する",
    phraseReading: "もんだいてん を してき する",
    phraseMeaning: "to point out a problem",
    sentence: "先生は文章の誤りを指摘した。",
    sentenceReading: "せんせい は ぶんしょう の あやまり を してき した。",
    sentenceMeaning: "The teacher pointed out the errors in the essay.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4569,
    subcategory: "Opinions & Arguments",
    folder: "opinions-arguments",
    word: "説得",
    reading: "せっとく",
    meaning: "persuasion",
    phrase: "相手を説得する",
    phraseReading: "あいて を せっとく する",
    phraseMeaning: "to persuade the other person",
    sentence: "彼を説得するのに時間がかかった。",
    sentenceReading: "かれ を せっとく する の に じかん が かかった。",
    sentenceMeaning: "It took time to persuade him.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4570,
    subcategory: "Opinions & Arguments",
    folder: "opinions-arguments",
    word: "納得",
    reading: "なっとく",
    meaning: "understanding; acceptance",
    phrase: "説明に納得する",
    phraseReading: "せつめい に なっとく する",
    phraseMeaning: "to accept an explanation",
    sentence: "彼の説明を聞いてやっと納得した。",
    sentenceReading: "かれ の せつめい を きいて やっと なっとく した。",
    sentenceMeaning: "After hearing his explanation, I finally understood and accepted it.",
    wordType: "noun / suru-verb",
  },

  // ── Lesson 571–580 · Personality & Character ───────────────
  {
    id: 4571,
    subcategory: "Personality & Character",
    folder: "personality-character",
    word: "穏やか",
    reading: "おだやか",
    meaning: "calm; gentle",
    phrase: "穏やかな性格",
    phraseReading: "おだやか な せいかく",
    phraseMeaning: "a calm and gentle personality",
    sentence: "彼女はいつも穏やかな態度で人と接する。",
    sentenceReading: "かのじょ は いつも おだやか な たいど で ひと と せっする。",
    sentenceMeaning: "She always deals with people in a calm manner.",
    wordType: "na-adjective",
  },
  {
    id: 4572,
    subcategory: "Personality & Character",
    folder: "personality-character",
    word: "素直",
    reading: "すなお",
    meaning: "honest; obedient",
    phrase: "素直な性格",
    phraseReading: "すなお な せいかく",
    phraseMeaning: "an honest, obedient personality",
    sentence: "あの子は素直で親の言うことをよく聞く。",
    sentenceReading: "あの こ は すなお で おや の いう こと を よく きく。",
    sentenceMeaning: "That child is obedient and listens well to what their parents say.",
    wordType: "na-adjective",
  },
  {
    id: 4573,
    subcategory: "Personality & Character",
    folder: "personality-character",
    word: "慎重",
    reading: "しんちょう",
    meaning: "cautious",
    phrase: "慎重に判断する",
    phraseReading: "しんちょう に はんだん する",
    phraseMeaning: "to judge cautiously",
    sentence: "大事な決断だから慎重に考えたい。",
    sentenceReading: "だいじ な けつだん だから しんちょう に かんがえたい。",
    sentenceMeaning: "Since it's an important decision, I want to think about it carefully.",
    wordType: "na-adjective",
  },
  {
    id: 4574,
    subcategory: "Personality & Character",
    folder: "personality-character",
    word: "大胆",
    reading: "だいたん",
    meaning: "bold; daring",
    phrase: "大胆な提案",
    phraseReading: "だいたん な ていあん",
    phraseMeaning: "a bold proposal",
    sentence: "彼は会議で大胆な意見を述べた。",
    sentenceReading: "かれ は かいぎ で だいたん な いけん を のべた。",
    sentenceMeaning: "He stated a bold opinion at the meeting.",
    wordType: "na-adjective",
  },
  {
    id: 4575,
    subcategory: "Personality & Character",
    folder: "personality-character",
    word: "冷静",
    reading: "れいせい",
    meaning: "calm; composed",
    phrase: "冷静に対応する",
    phraseReading: "れいせい に たいおう する",
    phraseMeaning: "to respond calmly",
    sentence: "緊急事態でも彼は冷静さを失わなかった。",
    sentenceReading: "きんきゅう じたい でも かれ は れいせい さ を うしなわなかった。",
    sentenceMeaning: "Even in an emergency, he did not lose his composure.",
    wordType: "na-adjective",
  },
  {
    id: 4576,
    subcategory: "Personality & Character",
    folder: "personality-character",
    word: "責任感",
    reading: "せきにんかん",
    meaning: "sense of responsibility",
    phrase: "責任感が強い",
    phraseReading: "せきにんかん が つよい",
    phraseMeaning: "to have a strong sense of responsibility",
    sentence: "彼女は責任感が強く、仕事を最後までやり遂げる。",
    sentenceReading: "かのじょ は せきにんかん が つよく、しごと を さいご まで やりとげる。",
    sentenceMeaning: "She has a strong sense of responsibility and sees work through to the end.",
    wordType: "noun",
  },
  {
    id: 4577,
    subcategory: "Personality & Character",
    folder: "personality-character",
    word: "協調性",
    reading: "きょうちょうせい",
    meaning: "cooperativeness",
    phrase: "協調性を大切にする",
    phraseReading: "きょうちょうせい を たいせつ に する",
    phraseMeaning: "to value cooperativeness",
    sentence: "チームで働くには協調性が必要だ。",
    sentenceReading: "ちーむ で はたらく に は きょうちょうせい が ひつよう だ。",
    sentenceMeaning: "Cooperativeness is necessary to work in a team.",
    wordType: "noun",
  },
  {
    id: 4578,
    subcategory: "Personality & Character",
    folder: "personality-character",
    word: "頑固",
    reading: "がんこ",
    meaning: "stubborn",
    phrase: "頑固な性格",
    phraseReading: "がんこ な せいかく",
    phraseMeaning: "a stubborn personality",
    sentence: "祖父はとても頑固で意見を変えない。",
    sentenceReading: "そふ は とても がんこ で いけん を かえない。",
    sentenceMeaning: "My grandfather is very stubborn and never changes his opinion.",
    wordType: "na-adjective",
  },
  {
    id: 4579,
    subcategory: "Personality & Character",
    folder: "personality-character",
    word: "向上心",
    reading: "こうじょうしん",
    meaning: "desire for self-improvement",
    phrase: "向上心を持つ",
    phraseReading: "こうじょうしん を もつ",
    phraseMeaning: "to have a desire for self-improvement",
    sentence: "彼はいつも向上心を持って新しいことに挑戦する。",
    sentenceReading: "かれ は いつも こうじょうしん を もって あたらしい こと に ちょうせん する。",
    sentenceMeaning: "He always takes on new challenges with a desire to improve himself.",
    wordType: "noun",
  },
  {
    id: 4580,
    subcategory: "Personality & Character",
    folder: "personality-character",
    word: "弾力",
    reading: "だんりょく",
    meaning: "elasticity; resilience",
    phrase: "弾力のある素材",
    phraseReading: "だんりょく の ある そざい",
    phraseMeaning: "an elastic material",
    sentence: "このゴムは弾力があって曲げやすい。",
    sentenceReading: "この ごむ は だんりょく が あって まげやすい。",
    sentenceMeaning: "This rubber is elastic and easy to bend.",
    wordType: "noun",
  },

  // ── Lesson 581–590 · Conflict & Relationships ───────────────
  {
    id: 4581,
    subcategory: "Conflict & Relationships",
    folder: "conflict-relationships",
    word: "対立",
    reading: "たいりつ",
    meaning: "conflict; opposition",
    phrase: "意見が対立する",
    phraseReading: "いけん が たいりつ する",
    phraseMeaning: "opinions to be in conflict",
    sentence: "二つのグループの間で意見が対立した。",
    sentenceReading: "ふたつ の ぐるーぷ の あいだ で いけん が たいりつ した。",
    sentenceMeaning: "Opinions clashed between the two groups.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4582,
    subcategory: "Conflict & Relationships",
    folder: "conflict-relationships",
    word: "衝突",
    reading: "しょうとつ",
    meaning: "collision; clash",
    phrase: "意見の衝突",
    phraseReading: "いけん の しょうとつ",
    phraseMeaning: "a clash of opinions",
    sentence: "兄弟の間でよく衝突が起きる。",
    sentenceReading: "きょうだい の あいだ で よく しょうとつ が おきる。",
    sentenceMeaning: "Clashes often occur between the siblings.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4583,
    subcategory: "Conflict & Relationships",
    folder: "conflict-relationships",
    word: "仲直り",
    reading: "なかなおり",
    meaning: "reconciliation",
    phrase: "友達と仲直りする",
    phraseReading: "ともだち と なかなおり する",
    phraseMeaning: "to make up with a friend",
    sentence: "けんかした翌日、二人は仲直りした。",
    sentenceReading: "けんか した よくじつ、ふたり は なかなおり した。",
    sentenceMeaning: "The day after their fight, the two made up.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4584,
    subcategory: "Conflict & Relationships",
    folder: "conflict-relationships",
    word: "信用",
    reading: "しんよう",
    meaning: "credit; trustworthiness",
    phrase: "信用を得る",
    phraseReading: "しんよう を える",
    phraseMeaning: "to gain trust",
    sentence: "彼は誠実な態度で人々の信用を得た。",
    sentenceReading: "かれ は せいじつ な たいど で ひとびと の しんよう を えた。",
    sentenceMeaning: "He gained people's trust through his sincere attitude.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4585,
    subcategory: "Conflict & Relationships",
    folder: "conflict-relationships",
    word: "裏切る",
    reading: "うらぎる",
    meaning: "to betray",
    phrase: "仲間を裏切る",
    phraseReading: "なかま を うらぎる",
    phraseMeaning: "to betray a companion",
    sentence: "彼は親友を裏切ってしまった。",
    sentenceReading: "かれ は しんゆう を うらぎって しまった。",
    sentenceMeaning: "He ended up betraying his close friend.",
    wordType: "verb (godan)",
  },
  {
    id: 4586,
    subcategory: "Conflict & Relationships",
    folder: "conflict-relationships",
    word: "責める",
    reading: "せめる",
    meaning: "to blame",
    phrase: "自分を責める",
    phraseReading: "じぶん を せめる",
    phraseMeaning: "to blame oneself",
    sentence: "失敗した部下を責めるのはよくない。",
    sentenceReading: "しっぱい した ぶか を せめる の は よくない。",
    sentenceMeaning: "It is not good to blame a subordinate who failed.",
    wordType: "verb (ichidan)",
  },
  {
    id: 4587,
    subcategory: "Conflict & Relationships",
    folder: "conflict-relationships",
    word: "許す",
    reading: "ゆるす",
    meaning: "to forgive; permit",
    phrase: "過ちを許す",
    phraseReading: "あやまち を ゆるす",
    phraseMeaning: "to forgive a mistake",
    sentence: "彼女は彼の過ちを許した。",
    sentenceReading: "かのじょ は かれ の あやまち を ゆるした。",
    sentenceMeaning: "She forgave his mistake.",
    wordType: "verb (godan)",
  },
  {
    id: 4588,
    subcategory: "Conflict & Relationships",
    folder: "conflict-relationships",
    word: "誤る",
    reading: "あやまる",
    meaning: "to make a mistake",
    phrase: "判断を誤る",
    phraseReading: "はんだん を あやまる",
    phraseMeaning: "to make a wrong judgment",
    sentence: "彼は判断を誤って大きな損をした。",
    sentenceReading: "かれ は はんだん を あやまって おおきな そん を した。",
    sentenceMeaning: "He made a wrong judgment and suffered a big loss.",
    wordType: "verb (godan)",
  },
  {
    id: 4589,
    subcategory: "Conflict & Relationships",
    folder: "conflict-relationships",
    word: "尊重",
    reading: "そんちょう",
    meaning: "respect",
    phrase: "相手の意見を尊重する",
    phraseReading: "あいて の いけん を そんちょう する",
    phraseMeaning: "to respect the other person's opinion",
    sentence: "互いの文化を尊重することが大切だ。",
    sentenceReading: "たがい の ぶんか を そんちょう する こと が たいせつ だ。",
    sentenceMeaning: "It is important to respect each other's culture.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4590,
    subcategory: "Conflict & Relationships",
    folder: "conflict-relationships",
    word: "歩み寄る",
    reading: "あゆみよる",
    meaning: "to make a compromise",
    phrase: "双方が歩み寄る",
    phraseReading: "そうほう が あゆみよる",
    phraseMeaning: "both sides to compromise",
    sentence: "話し合いの末、双方が少しずつ歩み寄った。",
    sentenceReading: "はなしあい の すえ、そうほう が すこし ずつ あゆみよった。",
    sentenceMeaning: "After discussion, both sides gradually reached a compromise.",
    wordType: "verb (godan)",
  },

  // ── Lesson 591–600 · Rules & Compliance ───────────────
  {
    id: 4591,
    subcategory: "Rules & Compliance",
    folder: "rules-compliance",
    word: "規則",
    reading: "きそく",
    meaning: "rule; regulation",
    phrase: "規則を守る",
    phraseReading: "きそく を まもる",
    phraseMeaning: "to follow the rules",
    sentence: "この学校には厳しい規則がある。",
    sentenceReading: "この がっこう に は きびしい きそく が ある。",
    sentenceMeaning: "This school has strict rules.",
    wordType: "noun",
  },
  {
    id: 4592,
    subcategory: "Rules & Compliance",
    folder: "rules-compliance",
    word: "規定",
    reading: "きてい",
    meaning: "provision; regulation",
    phrase: "規定に従う",
    phraseReading: "きてい に したがう",
    phraseMeaning: "to follow the regulations",
    sentence: "会社の規定に従って手続きを行った。",
    sentenceReading: "かいしゃ の きてい に したがって てつづき を おこなった。",
    sentenceMeaning: "I carried out the procedure in accordance with the company's regulations.",
    wordType: "noun",
  },
  {
    id: 4593,
    subcategory: "Rules & Compliance",
    folder: "rules-compliance",
    word: "基準",
    reading: "きじゅん",
    meaning: "standard; criterion",
    phrase: "判断の基準",
    phraseReading: "はんだん の きじゅん",
    phraseMeaning: "a criterion for judgment",
    sentence: "採用の基準が明確に決められている。",
    sentenceReading: "さいよう の きじゅん が めいかく に きめられて いる。",
    sentenceMeaning: "The hiring criteria are clearly defined.",
    wordType: "noun",
  },
  {
    id: 4594,
    subcategory: "Rules & Compliance",
    folder: "rules-compliance",
    word: "逸脱",
    reading: "いつだつ",
    meaning: "deviation; departure from norms",
    phrase: "規則から逸脱する",
    phraseReading: "きそく から いつだつ する",
    phraseMeaning: "to deviate from the rules",
    sentence: "彼の行動は常識から逸脱していた。",
    sentenceReading: "かれ の こうどう は じょうしき から いつだつ して いた。",
    sentenceMeaning: "His behavior deviated from common sense.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4595,
    subcategory: "Rules & Compliance",
    folder: "rules-compliance",
    word: "義務",
    reading: "ぎむ",
    meaning: "duty; obligation",
    phrase: "義務を果たす",
    phraseReading: "ぎむ を はたす",
    phraseMeaning: "to fulfill an obligation",
    sentence: "国民には税金を納める義務がある。",
    sentenceReading: "こくみん に は ぜいきん を おさめる ぎむ が ある。",
    sentenceMeaning: "Citizens have a duty to pay taxes.",
    wordType: "noun",
  },
  {
    id: 4596,
    subcategory: "Rules & Compliance",
    folder: "rules-compliance",
    word: "権利",
    reading: "けんり",
    meaning: "right; entitlement",
    phrase: "権利を守る",
    phraseReading: "けんり を まもる",
    phraseMeaning: "to protect a right",
    sentence: "誰にでも自由に発言する権利がある。",
    sentenceReading: "だれ に でも じゆう に はつげん する けんり が ある。",
    sentenceMeaning: "Everyone has the right to speak freely.",
    wordType: "noun",
  },
  {
    id: 4597,
    subcategory: "Rules & Compliance",
    folder: "rules-compliance",
    word: "厳守",
    reading: "げんしゅ",
    meaning: "strict observance",
    phrase: "時間を厳守する",
    phraseReading: "じかん を げんしゅ する",
    phraseMeaning: "to strictly observe the time",
    sentence: "会議では時間の厳守が求められる。",
    sentenceReading: "かいぎ で は じかん の げんしゅ が もとめられる。",
    sentenceMeaning: "Strict punctuality is required at meetings.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4598,
    subcategory: "Rules & Compliance",
    folder: "rules-compliance",
    word: "禁止",
    reading: "きんし",
    meaning: "prohibition",
    phrase: "立ち入りを禁止する",
    phraseReading: "たちいり を きんし する",
    phraseMeaning: "to prohibit entry",
    sentence: "この施設では撮影が禁止されている。",
    sentenceReading: "この しせつ で は さつえい が きんし されて いる。",
    sentenceMeaning: "Photography is prohibited at this facility.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4599,
    subcategory: "Rules & Compliance",
    folder: "rules-compliance",
    word: "施行",
    reading: "しこう",
    meaning: "enforcement; putting into effect",
    phrase: "法律が施行される",
    phraseReading: "ほうりつ が しこう される",
    phraseMeaning: "a law to be enforced",
    sentence: "新しい法律が来月から施行される。",
    sentenceReading: "あたらしい ほうりつ が らいげつ から しこう される。",
    sentenceMeaning: "The new law will take effect starting next month.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4600,
    subcategory: "Rules & Compliance",
    folder: "rules-compliance",
    word: "例外",
    reading: "れいがい",
    meaning: "exception",
    phrase: "例外を認める",
    phraseReading: "れいがい を みとめる",
    phraseMeaning: "to allow an exception",
    sentence: "この規則には例外がない。",
    sentenceReading: "この きそく に は れいがい が ない。",
    sentenceMeaning: "There is no exception to this rule.",
    wordType: "noun",
  },
