  // ── Lesson 701–710 · Causes & Consequences ───────────────────────
  {
    id: 4701,
    subcategory: "Causes & Consequences",
    folder: "causes-consequences",
    word: "原因",
    reading: "げんいん",
    meaning: "cause",
    phrase: "原因を調べる",
    phraseReading: "げんいん を しらべる",
    phraseMeaning: "to investigate the cause",
    sentence: "事故の原因はまだわかっていない。",
    sentenceReading: "じこ の げんいん は まだ わかって いない。",
    sentenceMeaning: "The cause of the accident is still unknown.",
    wordType: "noun",
  },
  {
    id: 4702,
    subcategory: "Causes & Consequences",
    folder: "causes-consequences",
    word: "要因",
    reading: "よういん",
    meaning: "factor",
    phrase: "成功の要因",
    phraseReading: "せいこう の よういん",
    phraseMeaning: "a factor of success",
    sentence: "売り上げ増加の要因はいくつかある。",
    sentenceReading: "うりあげ ぞうか の よういん は いくつか ある。",
    sentenceMeaning: "There are several factors behind the increase in sales.",
    wordType: "noun",
  },
  {
    id: 4703,
    subcategory: "Causes & Consequences",
    folder: "causes-consequences",
    word: "背景",
    reading: "はいけい",
    meaning: "background",
    phrase: "事件の背景",
    phraseReading: "じけん の はいけい",
    phraseMeaning: "the background of the incident",
    sentence: "この問題には複雑な背景がある。",
    sentenceReading: "この もんだい に は ふくざつ な はいけい が ある。",
    sentenceMeaning: "This problem has a complicated background.",
    wordType: "noun",
  },
  {
    id: 4704,
    subcategory: "Causes & Consequences",
    folder: "causes-consequences",
    word: "影響",
    reading: "えいきょう",
    meaning: "influence; effect",
    phrase: "影響を受ける",
    phraseReading: "えいきょう を うける",
    phraseMeaning: "to be influenced",
    sentence: "天候は農業に大きな影響を与える。",
    sentenceReading: "てんこう は のうぎょう に おおきな えいきょう を あたえる。",
    sentenceMeaning: "Weather has a big influence on agriculture.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4705,
    subcategory: "Causes & Consequences",
    folder: "causes-consequences",
    word: "結果",
    reading: "けっか",
    meaning: "result",
    phrase: "結果を出す",
    phraseReading: "けっか を だす",
    phraseMeaning: "to produce a result",
    sentence: "努力の結果、試験に合格した。",
    sentenceReading: "どりょく の けっか、しけん に ごうかく した。",
    sentenceMeaning: "As a result of his effort, he passed the exam.",
    wordType: "noun",
  },
  {
    id: 4706,
    subcategory: "Causes & Consequences",
    folder: "causes-consequences",
    word: "効力",
    reading: "こうりょく",
    meaning: "efficacy; legal effect",
    phrase: "効力を発する",
    phraseReading: "こうりょく を はっする",
    phraseMeaning: "to take effect",
    sentence: "この契約は来月から効力を持つ。",
    sentenceReading: "この けいやく は らいげつ から こうりょく を もつ。",
    sentenceMeaning: "This contract will take effect from next month.",
    wordType: "noun",
  },
  {
    id: 4707,
    subcategory: "Causes & Consequences",
    folder: "causes-consequences",
    word: "打撃",
    reading: "だげき",
    meaning: "blow; hit; serious damage",
    phrase: "経済に打撃を与える",
    phraseReading: "けいざい に だげき を あたえる",
    phraseMeaning: "to deal a blow to the economy",
    sentence: "台風は農作物に大きな打撃を与えた。",
    sentenceReading: "たいふう は のうさくぶつ に おおきな だげき を あたえた。",
    sentenceMeaning: "The typhoon dealt a big blow to the crops.",
    wordType: "noun",
  },
  {
    id: 4708,
    subcategory: "Causes & Consequences",
    folder: "causes-consequences",
    word: "負担",
    reading: "ふたん",
    meaning: "burden",
    phrase: "負担を軽減する",
    phraseReading: "ふたん を けいげん する",
    phraseMeaning: "to reduce the burden",
    sentence: "医療費の負担が家計を苦しめている。",
    sentenceReading: "いりょうひ の ふたん が かけい を くるしめて いる。",
    sentenceMeaning: "The burden of medical expenses is straining the household budget.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4709,
    subcategory: "Causes & Consequences",
    folder: "causes-consequences",
    word: "きっかけ",
    reading: "きっかけ",
    meaning: "trigger; opportunity",
    phrase: "きっかけをつかむ",
    phraseReading: "きっかけ を つかむ",
    phraseMeaning: "to seize an opportunity",
    sentence: "友人の一言が留学を決めるきっかけになった。",
    sentenceReading: "ゆうじん の ひとこと が りゅうがく を きめる きっかけ に なった。",
    sentenceMeaning: "A friend's remark became the trigger for deciding to study abroad.",
    wordType: "noun",
  },
  {
    id: 4710,
    subcategory: "Causes & Consequences",
    folder: "causes-consequences",
    word: "招く",
    reading: "まねく",
    meaning: "to cause; invite",
    phrase: "誤解を招く",
    phraseReading: "ごかい を まねく",
    phraseMeaning: "to invite misunderstanding",
    sentence: "その発言は多くの批判を招いた。",
    sentenceReading: "その はつげん は おおくの ひはん を まねいた。",
    sentenceMeaning: "That remark invited a lot of criticism.",
    wordType: "verb (godan)",
  },

  // ── Lesson 711–720 · Possibility & Prediction ────────────────────
  {
    id: 4711,
    subcategory: "Possibility & Prediction",
    folder: "possibility-prediction",
    word: "可能性",
    reading: "かのうせい",
    meaning: "possibility",
    phrase: "可能性が高い",
    phraseReading: "かのうせい が たかい",
    phraseMeaning: "the possibility is high",
    sentence: "この計画が成功する可能性は高い。",
    sentenceReading: "この けいかく が せいこう する かのうせい は たかい。",
    sentenceMeaning: "The possibility that this plan will succeed is high.",
    wordType: "noun",
  },
  {
    id: 4712,
    subcategory: "Possibility & Prediction",
    folder: "possibility-prediction",
    word: "見込み",
    reading: "みこみ",
    meaning: "prospect; likelihood",
    phrase: "回復の見込み",
    phraseReading: "かいふく の みこみ",
    phraseMeaning: "prospect of recovery",
    sentence: "病気は来週には治る見込みだ。",
    sentenceReading: "びょうき は らいしゅう に は なおる みこみ だ。",
    sentenceMeaning: "The illness is expected to heal by next week.",
    wordType: "noun",
  },
  {
    id: 4713,
    subcategory: "Possibility & Prediction",
    folder: "possibility-prediction",
    word: "予測",
    reading: "よそく",
    meaning: "prediction",
    phrase: "将来を予測する",
    phraseReading: "しょうらい を よそく する",
    phraseMeaning: "to predict the future",
    sentence: "専門家は経済の動きを予測した。",
    sentenceReading: "せんもんか は けいざい の うごき を よそく した。",
    sentenceMeaning: "The expert predicted the movement of the economy.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4714,
    subcategory: "Possibility & Prediction",
    folder: "possibility-prediction",
    word: "推測",
    reading: "すいそく",
    meaning: "conjecture; estimation",
    phrase: "事情を推測する",
    phraseReading: "じじょう を すいそく する",
    phraseMeaning: "to guess at the circumstances",
    sentence: "彼の様子から何かあったと推測した。",
    sentenceReading: "かれ の ようす から なにか あった と すいそく した。",
    sentenceMeaning: "From his appearance, I guessed that something had happened.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4715,
    subcategory: "Possibility & Prediction",
    folder: "possibility-prediction",
    word: "想定",
    reading: "そうてい",
    meaning: "assumption; supposition",
    phrase: "最悪の事態を想定する",
    phraseReading: "さいあく の じたい を そうてい する",
    phraseMeaning: "to assume the worst-case scenario",
    sentence: "地震に備えて避難計画を想定しておく。",
    sentenceReading: "じしん に そなえて ひなん けいかく を そうてい して おく。",
    sentenceMeaning: "We prepare an evacuation plan in anticipation of an earthquake.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4716,
    subcategory: "Possibility & Prediction",
    folder: "possibility-prediction",
    word: "確実",
    reading: "かくじつ",
    meaning: "certain; reliable",
    phrase: "確実な情報",
    phraseReading: "かくじつ な じょうほう",
    phraseMeaning: "reliable information",
    sentence: "彼の合格はほぼ確実だ。",
    sentenceReading: "かれ の ごうかく は ほぼ かくじつ だ。",
    sentenceMeaning: "His passing is almost certain.",
    wordType: "na-adjective",
  },
  {
    id: 4717,
    subcategory: "Possibility & Prediction",
    folder: "possibility-prediction",
    word: "明らか",
    reading: "あきらか",
    meaning: "clear; evident",
    phrase: "原因を明らかにする",
    phraseReading: "げんいん を あきらか に する",
    phraseMeaning: "to clarify the cause",
    sentence: "調査で事故の原因が明らかになった。",
    sentenceReading: "ちょうさ で じこ の げんいん が あきらか に なった。",
    sentenceMeaning: "The cause of the accident became clear through the investigation.",
    wordType: "na-adjective",
  },
  {
    id: 4718,
    subcategory: "Possibility & Prediction",
    folder: "possibility-prediction",
    word: "おそらく",
    reading: "おそらく",
    meaning: "probably",
    phrase: "おそらく雨だろう",
    phraseReading: "おそらく あめ だろう",
    phraseMeaning: "it will probably rain",
    sentence: "おそらく彼は約束を忘れているだろう。",
    sentenceReading: "おそらく かれ は やくそく を わすれて いる だろう。",
    sentenceMeaning: "He has probably forgotten the promise.",
    wordType: "adverb",
  },
  {
    id: 4719,
    subcategory: "Possibility & Prediction",
    folder: "possibility-prediction",
    word: "万一",
    reading: "まんいち",
    meaning: "in the unlikely event",
    phrase: "万一の場合",
    phraseReading: "まんいち の ばあい",
    phraseMeaning: "in case of emergency",
    sentence: "万一のために保険に入っておいた。",
    sentenceReading: "まんいち の ため に ほけん に はいって おいた。",
    sentenceMeaning: "I took out insurance just in case.",
    wordType: "noun / adverb",
  },
  {
    id: 4720,
    subcategory: "Possibility & Prediction",
    folder: "possibility-prediction",
    word: "見通し",
    reading: "みとおし",
    meaning: "outlook; forecast",
    phrase: "景気の見通し",
    phraseReading: "けいき の みとおし",
    phraseMeaning: "economic outlook",
    sentence: "今後の経済の見通しは不透明だ。",
    sentenceReading: "こんご の けいざい の みとおし は ふとうめい だ。",
    sentenceMeaning: "The future economic outlook is unclear.",
    wordType: "noun",
  },

  // ── Lesson 721–730 · Evaluation & Comparison ─────────────────────
  {
    id: 4721,
    subcategory: "Evaluation & Comparison",
    folder: "evaluation-comparison",
    word: "査定",
    reading: "さてい",
    meaning: "assessment; appraisal",
    phrase: "車を査定する",
    phraseReading: "くるま を さてい する",
    phraseMeaning: "to appraise a car",
    sentence: "中古車の価値を査定してもらった。",
    sentenceReading: "ちゅうこしゃ の かち を さてい して もらった。",
    sentenceMeaning: "I had the value of the used car appraised.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4722,
    subcategory: "Evaluation & Comparison",
    folder: "evaluation-comparison",
    word: "比較",
    reading: "ひかく",
    meaning: "comparison",
    phrase: "価格を比較する",
    phraseReading: "かかく を ひかく する",
    phraseMeaning: "to compare prices",
    sentence: "複数の店で価格を比較してから買った。",
    sentenceReading: "ふくすう の みせ で かかく を ひかく して から かった。",
    sentenceMeaning: "I compared prices at several stores before buying.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4723,
    subcategory: "Evaluation & Comparison",
    folder: "evaluation-comparison",
    word: "優れる",
    reading: "すぐれる",
    meaning: "to excel; be superior",
    phrase: "性能が優れる",
    phraseReading: "せいのう が すぐれる",
    phraseMeaning: "the performance is superior",
    sentence: "このソフトは操作性に優れている。",
    sentenceReading: "この そふと は そうさせい に すぐれて いる。",
    sentenceMeaning: "This software excels in usability.",
    wordType: "verb (ichidan)",
  },
  {
    id: 4724,
    subcategory: "Evaluation & Comparison",
    folder: "evaluation-comparison",
    word: "劣る",
    reading: "おとる",
    meaning: "to be inferior",
    phrase: "品質が劣る",
    phraseReading: "ひんしつ が おとる",
    phraseMeaning: "the quality is inferior",
    sentence: "新製品は旧製品に比べて性能が劣る。",
    sentenceReading: "しんせいひん は きゅうせいひん に くらべて せいのう が おとる。",
    sentenceMeaning: "The new product is inferior in performance compared to the old one.",
    wordType: "verb (godan)",
  },
  {
    id: 4725,
    subcategory: "Evaluation & Comparison",
    folder: "evaluation-comparison",
    word: "適切",
    reading: "てきせつ",
    meaning: "appropriate",
    phrase: "適切な対応",
    phraseReading: "てきせつ な たいおう",
    phraseMeaning: "appropriate response",
    sentence: "問題には適切に対応する必要がある。",
    sentenceReading: "もんだい に は てきせつ に たいおう する ひつよう が ある。",
    sentenceMeaning: "It is necessary to respond appropriately to the problem.",
    wordType: "na-adjective",
  },
  {
    id: 4726,
    subcategory: "Evaluation & Comparison",
    folder: "evaluation-comparison",
    word: "不十分",
    reading: "ふじゅうぶん",
    meaning: "insufficient",
    phrase: "説明が不十分だ",
    phraseReading: "せつめい が ふじゅうぶん だ",
    phraseMeaning: "the explanation is insufficient",
    sentence: "準備が不十分なまま試合に出た。",
    sentenceReading: "じゅんび が ふじゅうぶん な まま しあい に でた。",
    sentenceMeaning: "He entered the match with insufficient preparation.",
    wordType: "na-adjective",
  },
  {
    id: 4727,
    subcategory: "Evaluation & Comparison",
    folder: "evaluation-comparison",
    word: "有効",
    reading: "ゆうこう",
    meaning: "effective; valid",
    phrase: "有効な手段",
    phraseReading: "ゆうこう な しゅだん",
    phraseMeaning: "effective means",
    sentence: "このチケットは今日まで有効だ。",
    sentenceReading: "この ちけっと は きょう まで ゆうこう だ。",
    sentenceMeaning: "This ticket is valid until today.",
    wordType: "na-adjective",
  },
  {
    id: 4728,
    subcategory: "Evaluation & Comparison",
    folder: "evaluation-comparison",
    word: "無効",
    reading: "むこう",
    meaning: "invalid; ineffective",
    phrase: "契約を無効にする",
    phraseReading: "けいやく を むこう に する",
    phraseMeaning: "to invalidate a contract",
    sentence: "期限切れのパスポートは無効だ。",
    sentenceReading: "きげんぎれ の ぱすぽーと は むこう だ。",
    sentenceMeaning: "An expired passport is invalid.",
    wordType: "na-adjective",
  },
  {
    id: 4729,
    subcategory: "Evaluation & Comparison",
    folder: "evaluation-comparison",
    word: "公平",
    reading: "こうへい",
    meaning: "fair; impartial",
    phrase: "公平な判断",
    phraseReading: "こうへい な はんだん",
    phraseMeaning: "a fair judgment",
    sentence: "審判は公平にルールを適用した。",
    sentenceReading: "しんぱん は こうへい に るーる を てきよう した。",
    sentenceMeaning: "The referee applied the rules fairly.",
    wordType: "na-adjective",
  },
  {
    id: 4730,
    subcategory: "Evaluation & Comparison",
    folder: "evaluation-comparison",
    word: "客観的",
    reading: "きゃっかんてき",
    meaning: "objective",
    phrase: "客観的な意見",
    phraseReading: "きゃっかんてき な いけん",
    phraseMeaning: "an objective opinion",
    sentence: "この報告書は客観的な立場で書かれている。",
    sentenceReading: "この ほうこくしょ は きゃっかんてき な たちば で かかれて いる。",
    sentenceMeaning: "This report is written from an objective standpoint.",
    wordType: "na-adjective",
  },

  // ── Lesson 731–740 · Academic Reading ────────────────────────────
  {
    id: 4731,
    subcategory: "Academic Reading",
    folder: "academic-reading",
    word: "概要",
    reading: "がいよう",
    meaning: "outline; overview",
    phrase: "計画の概要",
    phraseReading: "けいかく の がいよう",
    phraseMeaning: "the outline of the plan",
    sentence: "まず本の概要を説明します。",
    sentenceReading: "まず ほん の がいよう を せつめい します。",
    sentenceMeaning: "First, I will explain the outline of the book.",
    wordType: "noun",
  },
  {
    id: 4732,
    subcategory: "Academic Reading",
    folder: "academic-reading",
    word: "内容",
    reading: "ないよう",
    meaning: "contents",
    phrase: "内容を確認する",
    phraseReading: "ないよう を かくにん する",
    phraseMeaning: "to check the contents",
    sentence: "この本の内容は難しくて理解しにくい。",
    sentenceReading: "この ほん の ないよう は むずかしくて りかい しにくい。",
    sentenceMeaning: "The content of this book is difficult and hard to understand.",
    wordType: "noun",
  },
  {
    id: 4733,
    subcategory: "Academic Reading",
    folder: "academic-reading",
    word: "項目",
    reading: "こうもく",
    meaning: "item; heading",
    phrase: "項目に分ける",
    phraseReading: "こうもく に わける",
    phraseMeaning: "to divide into items",
    sentence: "申込書にはいくつかの項目がある。",
    sentenceReading: "もうしこみしょ に は いくつか の こうもく が ある。",
    sentenceMeaning: "There are several items on the application form.",
    wordType: "noun",
  },
  {
    id: 4734,
    subcategory: "Academic Reading",
    folder: "academic-reading",
    word: "要点",
    reading: "ようてん",
    meaning: "main point",
    phrase: "要点をまとめる",
    phraseReading: "ようてん を まとめる",
    phraseMeaning: "to summarize the main points",
    sentence: "会議の要点をメモしておいた。",
    sentenceReading: "かいぎ の ようてん を めも して おいた。",
    sentenceMeaning: "I took notes on the main points of the meeting.",
    wordType: "noun",
  },
  {
    id: 4735,
    subcategory: "Academic Reading",
    folder: "academic-reading",
    word: "具体例",
    reading: "ぐたいれい",
    meaning: "concrete example",
    phrase: "具体例を挙げる",
    phraseReading: "ぐたいれい を あげる",
    phraseMeaning: "to give a concrete example",
    sentence: "先生は説明のために具体例を示した。",
    sentenceReading: "せんせい は せつめい の ため に ぐたいれい を しめした。",
    sentenceMeaning: "The teacher gave a concrete example for the explanation.",
    wordType: "noun",
  },
  {
    id: 4736,
    subcategory: "Academic Reading",
    folder: "academic-reading",
    word: "定義",
    reading: "ていぎ",
    meaning: "definition",
    phrase: "言葉を定義する",
    phraseReading: "ことば を ていぎ する",
    phraseMeaning: "to define a word",
    sentence: "このレポートでは成功を定義する必要がある。",
    sentenceReading: "この れぽーと で は せいこう を ていぎ する ひつよう が ある。",
    sentenceMeaning: "In this report, it is necessary to define success.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4737,
    subcategory: "Academic Reading",
    folder: "academic-reading",
    word: "概念",
    reading: "がいねん",
    meaning: "concept",
    phrase: "新しい概念を導入する",
    phraseReading: "あたらしい がいねん を どうにゅう する",
    phraseMeaning: "to introduce a new concept",
    sentence: "この理論は難しい概念を含んでいる。",
    sentenceReading: "この りろん は むずかしい がいねん を ふくんで いる。",
    sentenceMeaning: "This theory contains a difficult concept.",
    wordType: "noun",
  },
  {
    id: 4738,
    subcategory: "Academic Reading",
    folder: "academic-reading",
    word: "文脈",
    reading: "ぶんみゃく",
    meaning: "context",
    phrase: "文脈から判断する",
    phraseReading: "ぶんみゃく から はんだん する",
    phraseMeaning: "to judge from the context",
    sentence: "言葉の意味は文脈によって変わる。",
    sentenceReading: "ことば の いみ は ぶんみゃく に よって かわる。",
    sentenceMeaning: "The meaning of a word changes depending on the context.",
    wordType: "noun",
  },
  {
    id: 4739,
    subcategory: "Academic Reading",
    folder: "academic-reading",
    word: "引用",
    reading: "いんよう",
    meaning: "quotation; citation",
    phrase: "文章を引用する",
    phraseReading: "ぶんしょう を いんよう する",
    phraseMeaning: "to quote a passage",
    sentence: "レポートでは専門家の言葉を引用した。",
    sentenceReading: "れぽーと で は せんもんか の ことば を いんよう した。",
    sentenceMeaning: "In the report, I quoted the words of an expert.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4740,
    subcategory: "Academic Reading",
    folder: "academic-reading",
    word: "結論",
    reading: "けつろん",
    meaning: "conclusion",
    phrase: "結論を出す",
    phraseReading: "けつろん を だす",
    phraseMeaning: "to reach a conclusion",
    sentence: "長い議論の末、結論に達した。",
    sentenceReading: "ながい ぎろん の すえ、けつろん に たっした。",
    sentenceMeaning: "After a long discussion, we reached a conclusion.",
    wordType: "noun / suru-verb",
  },

  // ── Lesson 741–750 · Abstract Verbs ───────────────────────────────
  {
    id: 4741,
    subcategory: "Abstract Verbs",
    folder: "abstract-verbs",
    word: "生じる",
    reading: "しょうじる",
    meaning: "to arise; occur",
    phrase: "問題が生じる",
    phraseReading: "もんだい が しょうじる",
    phraseMeaning: "a problem arises",
    sentence: "工事の遅れによって様々な問題が生じた。",
    sentenceReading: "こうじ の おくれ に よって さまざまな もんだい が しょうじた。",
    sentenceMeaning: "Various problems arose due to the delay in construction.",
    wordType: "verb (ichidan)",
  },
  {
    id: 4742,
    subcategory: "Abstract Verbs",
    folder: "abstract-verbs",
    word: "及ぼす",
    reading: "およぼす",
    meaning: "to exert; cause",
    phrase: "影響を及ぼす",
    phraseReading: "えいきょう を およぼす",
    phraseMeaning: "to exert an influence",
    sentence: "気候変動は農業に大きな影響を及ぼす。",
    sentenceReading: "きこう へんどう は のうぎょう に おおきな えいきょう を およぼす。",
    sentenceMeaning: "Climate change exerts a great influence on agriculture.",
    wordType: "verb (godan)",
  },
  {
    id: 4743,
    subcategory: "Abstract Verbs",
    folder: "abstract-verbs",
    word: "伴う",
    reading: "ともなう",
    meaning: "to accompany",
    phrase: "リスクを伴う",
    phraseReading: "りすく を ともなう",
    phraseMeaning: "to be accompanied by risk",
    sentence: "この手術には危険が伴う。",
    sentenceReading: "この しゅじゅつ に は きけん が ともなう。",
    sentenceMeaning: "This operation is accompanied by danger.",
    wordType: "verb (godan)",
  },
  {
    id: 4744,
    subcategory: "Abstract Verbs",
    folder: "abstract-verbs",
    word: "基づく",
    reading: "もとづく",
    meaning: "to be based on",
    phrase: "事実に基づく",
    phraseReading: "じじつ に もとづく",
    phraseMeaning: "to be based on fact",
    sentence: "この映画は実話に基づいている。",
    sentenceReading: "この えいが は じつわ に もとづいて いる。",
    sentenceMeaning: "This movie is based on a true story.",
    wordType: "verb (godan)",
  },
  {
    id: 4745,
    subcategory: "Abstract Verbs",
    folder: "abstract-verbs",
    word: "占める",
    reading: "しめる",
    meaning: "to account for; occupy",
    phrase: "大きな割合を占める",
    phraseReading: "おおきな わりあい を しめる",
    phraseMeaning: "to account for a large proportion",
    sentence: "輸出は経済の重要な部分を占めている。",
    sentenceReading: "ゆしゅつ は けいざい の じゅうよう な ぶぶん を しめて いる。",
    sentenceMeaning: "Exports occupy an important part of the economy.",
    wordType: "verb (ichidan)",
  },
  {
    id: 4746,
    subcategory: "Abstract Verbs",
    folder: "abstract-verbs",
    word: "防ぐ",
    reading: "ふせぐ",
    meaning: "to prevent",
    phrase: "事故を防ぐ",
    phraseReading: "じこ を ふせぐ",
    phraseMeaning: "to prevent an accident",
    sentence: "手洗いは病気を防ぐのに効果的だ。",
    sentenceReading: "てあらい は びょうき を ふせぐ の に こうかてき だ。",
    sentenceMeaning: "Washing hands is effective in preventing illness.",
    wordType: "verb (godan)",
  },
  {
    id: 4747,
    subcategory: "Abstract Verbs",
    folder: "abstract-verbs",
    word: "避ける",
    reading: "さける",
    meaning: "to avoid",
    phrase: "危険を避ける",
    phraseReading: "きけん を さける",
    phraseMeaning: "to avoid danger",
    sentence: "混雑を避けて早めに出発した。",
    sentenceReading: "こんざつ を さけて はやめ に しゅっぱつ した。",
    sentenceMeaning: "I left early to avoid the crowds.",
    wordType: "verb (ichidan)",
  },
  {
    id: 4748,
    subcategory: "Abstract Verbs",
    folder: "abstract-verbs",
    word: "認める",
    reading: "みとめる",
    meaning: "to recognize; approve",
    phrase: "誤りを認める",
    phraseReading: "あやまり を みとめる",
    phraseMeaning: "to admit a mistake",
    sentence: "彼は自分の誤りを素直に認めた。",
    sentenceReading: "かれ は じぶん の あやまり を すなお に みとめた。",
    sentenceMeaning: "He honestly admitted his mistake.",
    wordType: "verb (ichidan)",
  },
  {
    id: 4749,
    subcategory: "Abstract Verbs",
    folder: "abstract-verbs",
    word: "求める",
    reading: "もとめる",
    meaning: "to seek; require",
    phrase: "改善を求める",
    phraseReading: "かいぜん を もとめる",
    phraseMeaning: "to demand improvement",
    sentence: "住民は市に対策を求めた。",
    sentenceReading: "じゅうみん は し に たいさく を もとめた。",
    sentenceMeaning: "The residents demanded countermeasures from the city.",
    wordType: "verb (ichidan)",
  },
  {
    id: 4750,
    subcategory: "Abstract Verbs",
    folder: "abstract-verbs",
    word: "限る",
    reading: "かぎる",
    meaning: "to limit; be restricted to",
    phrase: "会員に限る",
    phraseReading: "かいいん に かぎる",
    phraseMeaning: "limited to members",
    sentence: "このサービスは平日に限って利用できる。",
    sentenceReading: "この さーびす は へいじつ に かぎって りよう できる。",
    sentenceMeaning: "This service is available only on weekdays.",
    wordType: "verb (godan)",
  },
