  // ── Lesson 651–660 · Accidents & Insurance ───────────────────────
  {
    id: 4651,
    subcategory: "Accidents & Insurance",
    folder: "accidents-insurance",
    word: "事故",
    reading: "じこ",
    meaning: "accident",
    phrase: "事故を起こす",
    phraseReading: "じこ を おこす",
    phraseMeaning: "to cause an accident",
    sentence: "彼は雨の日に事故を起こしてしまった。",
    sentenceReading: "かれ は あめ の ひ に じこ を おこして しまった。",
    sentenceMeaning: "He ended up causing an accident on a rainy day.",
    wordType: "noun",
  },
  {
    id: 4652,
    subcategory: "Accidents & Insurance",
    folder: "accidents-insurance",
    word: "負傷",
    reading: "ふしょう",
    meaning: "injury",
    phrase: "負傷者を助ける",
    phraseReading: "ふしょうしゃ を たすける",
    phraseMeaning: "to help an injured person",
    sentence: "事故で多くの人が負傷した。",
    sentenceReading: "じこ で おおくの ひと が ふしょう した。",
    sentenceMeaning: "Many people were injured in the accident.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4653,
    subcategory: "Accidents & Insurance",
    folder: "accidents-insurance",
    word: "救出",
    reading: "きゅうしゅつ",
    meaning: "rescue; extrication",
    phrase: "救出作業を行う",
    phraseReading: "きゅうしゅつ さぎょう を おこなう",
    phraseMeaning: "to carry out rescue work",
    sentence: "消防士が閉じ込められた人を救出した。",
    sentenceReading: "しょうぼうし が とじこめられた ひと を きゅうしゅつ した。",
    sentenceMeaning: "The firefighter rescued the person who was trapped.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4654,
    subcategory: "Accidents & Insurance",
    folder: "accidents-insurance",
    word: "救急車",
    reading: "きゅうきゅうしゃ",
    meaning: "ambulance",
    phrase: "救急車を呼ぶ",
    phraseReading: "きゅうきゅうしゃ を よぶ",
    phraseMeaning: "to call an ambulance",
    sentence: "事故を見てすぐに救急車を呼んだ。",
    sentenceReading: "じこ を みて すぐに きゅうきゅうしゃ を よんだ。",
    sentenceMeaning: "I saw the accident and immediately called an ambulance.",
    wordType: "noun",
  },
  {
    id: 4655,
    subcategory: "Accidents & Insurance",
    folder: "accidents-insurance",
    word: "現場",
    reading: "げんば",
    meaning: "scene; work site",
    phrase: "事故の現場",
    phraseReading: "じこ の げんば",
    phraseMeaning: "the scene of the accident",
    sentence: "警察はすぐに現場に到着した。",
    sentenceReading: "けいさつ は すぐに げんば に とうちゃく した。",
    sentenceMeaning: "The police arrived at the scene immediately.",
    wordType: "noun",
  },
  {
    id: 4656,
    subcategory: "Accidents & Insurance",
    folder: "accidents-insurance",
    word: "損害",
    reading: "そんがい",
    meaning: "damage; loss",
    phrase: "損害を受ける",
    phraseReading: "そんがい を うける",
    phraseMeaning: "to suffer damage",
    sentence: "台風で家に大きな損害が出た。",
    sentenceReading: "たいふう で いえ に おおきな そんがい が でた。",
    sentenceMeaning: "The house suffered great damage from the typhoon.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4657,
    subcategory: "Accidents & Insurance",
    folder: "accidents-insurance",
    word: "補償",
    reading: "ほしょう",
    meaning: "compensation; indemnity",
    phrase: "損害を補償する",
    phraseReading: "そんがい を ほしょう する",
    phraseMeaning: "to compensate for damage",
    sentence: "保険会社が事故の被害を補償してくれた。",
    sentenceReading: "ほけん がいしゃ が じこ の ひがい を ほしょう して くれた。",
    sentenceMeaning: "The insurance company compensated for the damage from the accident.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4658,
    subcategory: "Accidents & Insurance",
    folder: "accidents-insurance",
    word: "過失",
    reading: "かしつ",
    meaning: "negligence; fault",
    phrase: "過失を認める",
    phraseReading: "かしつ を みとめる",
    phraseMeaning: "to admit fault",
    sentence: "運転手の過失で事故が起きた。",
    sentenceReading: "うんてんしゅ の かしつ で じこ が おきた。",
    sentenceMeaning: "The accident happened due to the driver's negligence.",
    wordType: "noun",
  },
  {
    id: 4659,
    subcategory: "Accidents & Insurance",
    folder: "accidents-insurance",
    word: "目撃者",
    reading: "もくげきしゃ",
    meaning: "witness",
    phrase: "目撃者が現れる",
    phraseReading: "もくげきしゃ が あらわれる",
    phraseMeaning: "a witness comes forward",
    sentence: "事故の目撃者が警察に証言した。",
    sentenceReading: "じこ の もくげきしゃ が けいさつ に しょうげん した。",
    sentenceMeaning: "The witness to the accident testified to the police.",
    wordType: "noun",
  },
  {
    id: 4660,
    subcategory: "Accidents & Insurance",
    folder: "accidents-insurance",
    word: "届け出",
    reading: "とどけで",
    meaning: "official notification",
    phrase: "届け出を出す",
    phraseReading: "とどけで を だす",
    phraseMeaning: "to submit an official notification",
    sentence: "事故があったら警察に届け出をする必要がある。",
    sentenceReading: "じこ が あったら けいさつ に とどけで を する ひつよう が ある。",
    sentenceMeaning: "If an accident occurs, you need to file a report with the police.",
    wordType: "noun",
  },

  // ── Lesson 661–670 · News & Public Information ───────────────────
  {
    id: 4661,
    subcategory: "News & Media",
    folder: "news-media",
    word: "特集",
    reading: "とくしゅう",
    meaning: "feature article; special coverage",
    phrase: "特集を組む",
    phraseReading: "とくしゅう を くむ",
    phraseMeaning: "to put together a feature article",
    sentence: "今週の雑誌は環境問題の特集を組んでいる。",
    sentenceReading: "こんしゅう の ざっし は かんきょう もんだい の とくしゅう を くんで いる。",
    sentenceMeaning: "This week's magazine has put together a feature on environmental issues.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4662,
    subcategory: "News & Media",
    folder: "news-media",
    word: "論説",
    reading: "ろんせつ",
    meaning: "editorial; opinion article",
    phrase: "論説を書く",
    phraseReading: "ろんせつ を かく",
    phraseMeaning: "to write an editorial",
    sentence: "新聞の論説を読んで社会の動きを知る。",
    sentenceReading: "しんぶん の ろんせつ を よんで しゃかい の うごき を しる。",
    sentenceMeaning: "I read the newspaper editorial to learn about what's happening in society.",
    wordType: "noun",
  },
  {
    id: 4663,
    subcategory: "News & Media",
    folder: "news-media",
    word: "見出し",
    reading: "みだし",
    meaning: "headline",
    phrase: "見出しをつける",
    phraseReading: "みだし を つける",
    phraseMeaning: "to add a headline",
    sentence: "新聞の見出しを見て記事の内容を予想した。",
    sentenceReading: "しんぶん の みだし を みて きじ の ないよう を よそう した。",
    sentenceMeaning: "I guessed the content of the article by looking at the newspaper headline.",
    wordType: "noun",
  },
  {
    id: 4664,
    subcategory: "News & Media",
    folder: "news-media",
    word: "速報",
    reading: "そくほう",
    meaning: "breaking news",
    phrase: "速報が入る",
    phraseReading: "そくほう が はいる",
    phraseMeaning: "breaking news comes in",
    sentence: "テレビで地震の速報が流れた。",
    sentenceReading: "てれび で じしん の そくほう が ながれた。",
    sentenceMeaning: "Breaking news about the earthquake was broadcast on TV.",
    wordType: "noun",
  },
  {
    id: 4665,
    subcategory: "News & Media",
    folder: "news-media",
    word: "会見",
    reading: "かいけん",
    meaning: "press conference; interview",
    phrase: "記者会見を行う",
    phraseReading: "きしゃ かいけん を おこなう",
    phraseMeaning: "to hold a press conference",
    sentence: "社長が事故について会見した。",
    sentenceReading: "しゃちょう が じこ に ついて かいけん した。",
    sentenceMeaning: "The president held a press conference about the accident.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4666,
    subcategory: "News & Media",
    folder: "news-media",
    word: "記者",
    reading: "きしゃ",
    meaning: "reporter",
    phrase: "記者に取材される",
    phraseReading: "きしゃ に しゅざい される",
    phraseMeaning: "to be interviewed by a reporter",
    sentence: "記者が現場で話を聞いていた。",
    sentenceReading: "きしゃ が げんば で はなし を きいて いた。",
    sentenceMeaning: "The reporter was listening to accounts at the scene.",
    wordType: "noun",
  },
  {
    id: 4667,
    subcategory: "News & Media",
    folder: "news-media",
    word: "世論",
    reading: "せろん",
    meaning: "public opinion",
    phrase: "世論を反映する",
    phraseReading: "せろん を はんえい する",
    phraseMeaning: "to reflect public opinion",
    sentence: "この政策には世論の反対が強い。",
    sentenceReading: "この せいさく に は せろん の はんたい が つよい。",
    sentenceMeaning: "There is strong public opposition to this policy.",
    wordType: "noun",
  },
  {
    id: 4668,
    subcategory: "News & Media",
    folder: "news-media",
    word: "公表",
    reading: "こうひょう",
    meaning: "public announcement",
    phrase: "結果を公表する",
    phraseReading: "けっか を こうひょう する",
    phraseMeaning: "to publicly announce the results",
    sentence: "会社は調査の結果を公表した。",
    sentenceReading: "かいしゃ は ちょうさ の けっか を こうひょう した。",
    sentenceMeaning: "The company publicly announced the results of the investigation.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4669,
    subcategory: "News & Media",
    folder: "news-media",
    word: "情報源",
    reading: "じょうほうげん",
    meaning: "information source",
    phrase: "情報源を明かす",
    phraseReading: "じょうほうげん を あかす",
    phraseMeaning: "to reveal one's information source",
    sentence: "記者は情報源を明らかにしなかった。",
    sentenceReading: "きしゃ は じょうほうげん を あきらか に しなかった。",
    sentenceMeaning: "The reporter did not reveal the information source.",
    wordType: "noun",
  },
  {
    id: 4670,
    subcategory: "News & Media",
    folder: "news-media",
    word: "訂正",
    reading: "ていせい",
    meaning: "correction",
    phrase: "記事を訂正する",
    phraseReading: "きじ を ていせい する",
    phraseMeaning: "to correct an article",
    sentence: "新聞は誤った記事を訂正した。",
    sentenceReading: "しんぶん は あやまった きじ を ていせい した。",
    sentenceMeaning: "The newspaper corrected the mistaken article.",
    wordType: "noun / suru-verb",
  },

  // ── Lesson 671–680 · Digital Security & Privacy ──────────────────
  {
    id: 4671,
    subcategory: "Digital Security & Privacy",
    folder: "digital-security",
    word: "個人情報",
    reading: "こじんじょうほう",
    meaning: "personal information",
    phrase: "個人情報を守る",
    phraseReading: "こじんじょうほう を まもる",
    phraseMeaning: "to protect personal information",
    sentence: "企業は個人情報の管理に注意を払っている。",
    sentenceReading: "きぎょう は こじんじょうほう の かんり に ちゅうい を はらって いる。",
    sentenceMeaning: "Companies pay careful attention to managing personal information.",
    wordType: "noun",
  },
  {
    id: 4672,
    subcategory: "Digital Security & Privacy",
    folder: "digital-security",
    word: "漏えい",
    reading: "ろうえい",
    meaning: "leak; disclosure",
    phrase: "情報が漏えいする",
    phraseReading: "じょうほう が ろうえい する",
    phraseMeaning: "information leaks",
    sentence: "顧客データの漏えいが発覚した。",
    sentenceReading: "こきゃく でーた の ろうえい が はっかく した。",
    sentenceMeaning: "A leak of customer data was discovered.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4673,
    subcategory: "Digital Security & Privacy",
    folder: "digital-security",
    word: "認証",
    reading: "にんしょう",
    meaning: "authentication",
    phrase: "本人認証を行う",
    phraseReading: "ほんにん にんしょう を おこなう",
    phraseMeaning: "to perform identity authentication",
    sentence: "このアプリは指紋で認証する。",
    sentenceReading: "この あぷり は しもん で にんしょう する。",
    sentenceMeaning: "This app authenticates using a fingerprint.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4674,
    subcategory: "Digital Security & Privacy",
    folder: "digital-security",
    word: "暗号化",
    reading: "あんごうか",
    meaning: "encryption",
    phrase: "データを暗号化する",
    phraseReading: "でーた を あんごうか する",
    phraseMeaning: "to encrypt data",
    sentence: "通信内容は暗号化されている。",
    sentenceReading: "つうしん ないよう は あんごうか されて いる。",
    sentenceMeaning: "The communication content is encrypted.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4675,
    subcategory: "Digital Security & Privacy",
    folder: "digital-security",
    word: "不正アクセス",
    reading: "ふせいアクセス",
    meaning: "unauthorized access",
    phrase: "不正アクセスを防ぐ",
    phraseReading: "ふせい あくせす を ふせぐ",
    phraseMeaning: "to prevent unauthorized access",
    sentence: "会社のシステムが不正な接続を受けた。",
    sentenceReading: "かいしゃ の しすてむ が ふせい な せつぞく を うけた。",
    sentenceMeaning: "The company's system was subjected to an unauthorized connection.",
    wordType: "noun",
  },
  {
    id: 4676,
    subcategory: "Digital Security & Privacy",
    folder: "digital-security",
    word: "脅威",
    reading: "きょうい",
    meaning: "threat",
    phrase: "脅威にさらされる",
    phraseReading: "きょうい に さらされる",
    phraseMeaning: "to be exposed to a threat",
    sentence: "外部からの攻撃は企業にとって大きな脅威だ。",
    sentenceReading: "がいぶ から の こうげき は きぎょう に とって おおきな きょうい だ。",
    sentenceMeaning: "Attacks from outside are a major threat to companies.",
    wordType: "noun",
  },
  {
    id: 4677,
    subcategory: "Digital Security & Privacy",
    folder: "digital-security",
    word: "対策",
    reading: "たいさく",
    meaning: "countermeasure",
    phrase: "対策を立てる",
    phraseReading: "たいさく を たてる",
    phraseMeaning: "to devise a countermeasure",
    sentence: "会社はセキュリティ対策を強化した。",
    sentenceReading: "かいしゃ は せきゅりてぃ たいさく を きょうか した。",
    sentenceMeaning: "The company strengthened its security measures.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4678,
    subcategory: "Digital Security & Privacy",
    folder: "digital-security",
    word: "監視",
    reading: "かんし",
    meaning: "monitoring; surveillance",
    phrase: "システムを監視する",
    phraseReading: "しすてむ を かんし する",
    phraseMeaning: "to monitor a system",
    sentence: "不審な動きがないか常に監視している。",
    sentenceReading: "ふしん な うごき が ない か つねに かんし して いる。",
    sentenceMeaning: "They are constantly monitoring for any suspicious activity.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4679,
    subcategory: "Digital Security & Privacy",
    folder: "digital-security",
    word: "復旧",
    reading: "ふっきゅう",
    meaning: "restoration; recovery",
    phrase: "復旧作業を進める",
    phraseReading: "ふっきゅう さぎょう を すすめる",
    phraseMeaning: "to proceed with restoration work",
    sentence: "停電からの復旧に数時間かかった。",
    sentenceReading: "ていでん から の ふっきゅう に すうじかん かかった。",
    sentenceMeaning: "It took several hours to recover from the power outage.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4680,
    subcategory: "Digital Security & Privacy",
    folder: "digital-security",
    word: "脆弱性",
    reading: "ぜいじゃくせい",
    meaning: "vulnerability",
    phrase: "脆弱性を修正する",
    phraseReading: "ぜいじゃくせい を しゅうせい する",
    phraseMeaning: "to fix a vulnerability",
    sentence: "ソフトウェアの脆弱性が発見された。",
    sentenceReading: "そふとうぇあ の ぜいじゃくせい が はっけん された。",
    sentenceMeaning: "A vulnerability in the software was discovered.",
    wordType: "noun",
  },

  // ── Lesson 681–690 · Science & Technology ────────────────────────
  {
    id: 4681,
    subcategory: "Science & Technology",
    folder: "science-technology",
    word: "技術",
    reading: "ぎじゅつ",
    meaning: "technology; skill",
    phrase: "技術を身につける",
    phraseReading: "ぎじゅつ を みに つける",
    phraseMeaning: "to acquire a skill",
    sentence: "彼は高い技術を持つ職人だ。",
    sentenceReading: "かれ は たかい ぎじゅつ を もつ しょくにん だ。",
    sentenceMeaning: "He is a craftsman with great skill.",
    wordType: "noun",
  },
  {
    id: 4682,
    subcategory: "Science & Technology",
    folder: "science-technology",
    word: "開発",
    reading: "かいはつ",
    meaning: "development",
    phrase: "新製品を開発する",
    phraseReading: "しんせいひん を かいはつ する",
    phraseMeaning: "to develop a new product",
    sentence: "この会社は新しい薬を開発している。",
    sentenceReading: "この かいしゃ は あたらしい くすり を かいはつ して いる。",
    sentenceMeaning: "This company is developing a new medicine.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4683,
    subcategory: "Science & Technology",
    folder: "science-technology",
    word: "発明",
    reading: "はつめい",
    meaning: "invention",
    phrase: "新しい機械を発明する",
    phraseReading: "あたらしい きかい を はつめい する",
    phraseMeaning: "to invent a new machine",
    sentence: "彼の発明は多くの人の生活を変えた。",
    sentenceReading: "かれ の はつめい は おおくの ひと の せいかつ を かえた。",
    sentenceMeaning: "His invention changed the lives of many people.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4684,
    subcategory: "Science & Technology",
    folder: "science-technology",
    word: "機器",
    reading: "きき",
    meaning: "equipment; apparatus",
    phrase: "医療機器を使う",
    phraseReading: "いりょう きき を つかう",
    phraseMeaning: "to use medical equipment",
    sentence: "工場には最新の機器が並んでいる。",
    sentenceReading: "こうじょう に は さいしん の きき が ならんで いる。",
    sentenceMeaning: "The latest equipment is lined up in the factory.",
    wordType: "noun",
  },
  {
    id: 4685,
    subcategory: "Science & Technology",
    folder: "science-technology",
    word: "機能",
    reading: "きのう",
    meaning: "function",
    phrase: "新しい機能を追加する",
    phraseReading: "あたらしい きのう を ついか する",
    phraseMeaning: "to add a new function",
    sentence: "このカメラには便利な機能がたくさんある。",
    sentenceReading: "この かめら に は べんり な きのう が たくさん ある。",
    sentenceMeaning: "This camera has many convenient functions.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4686,
    subcategory: "Science & Technology",
    folder: "science-technology",
    word: "性能",
    reading: "せいのう",
    meaning: "performance; capability",
    phrase: "性能が向上する",
    phraseReading: "せいのう が こうじょう する",
    phraseMeaning: "performance improves",
    sentence: "新型の車は性能が大きく向上した。",
    sentenceReading: "しんがた の くるま は せいのう が おおきく こうじょう した。",
    sentenceMeaning: "The performance of the new model car improved greatly.",
    wordType: "noun",
  },
  {
    id: 4687,
    subcategory: "Science & Technology",
    folder: "science-technology",
    word: "実験",
    reading: "じっけん",
    meaning: "experiment",
    phrase: "実験を行う",
    phraseReading: "じっけん を おこなう",
    phraseMeaning: "to conduct an experiment",
    sentence: "学生たちは教室で化学の実験をした。",
    sentenceReading: "がくせいたち は きょうしつ で かがく の じっけん を した。",
    sentenceMeaning: "The students conducted a chemistry experiment in the classroom.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4688,
    subcategory: "Science & Technology",
    folder: "science-technology",
    word: "導入",
    reading: "どうにゅう",
    meaning: "introduction; implementation",
    phrase: "新しい制度を導入する",
    phraseReading: "あたらしい せいど を どうにゅう する",
    phraseMeaning: "to introduce a new system",
    sentence: "会社は新しいシステムを導入した。",
    sentenceReading: "かいしゃ は あたらしい しすてむ を どうにゅう した。",
    sentenceMeaning: "The company introduced a new system.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4689,
    subcategory: "Science & Technology",
    folder: "science-technology",
    word: "機械化",
    reading: "きかいか",
    meaning: "mechanization",
    phrase: "作業を機械化する",
    phraseReading: "さぎょう を きかいか する",
    phraseMeaning: "to mechanize work",
    sentence: "農業の機械化が進んでいる。",
    sentenceReading: "のうぎょう の きかいか が すすんで いる。",
    sentenceMeaning: "The mechanization of agriculture is progressing.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4690,
    subcategory: "Science & Technology",
    folder: "science-technology",
    word: "先端技術",
    reading: "せんたんぎじゅつ",
    meaning: "cutting-edge technology",
    phrase: "先端技術を活用する",
    phraseReading: "せんたん ぎじゅつ を かつよう する",
    phraseMeaning: "to make use of cutting-edge technology",
    sentence: "この工場は先端技術を導入している。",
    sentenceReading: "この こうじょう は せんたん ぎじゅつ を どうにゅう して いる。",
    sentenceMeaning: "This factory has introduced cutting-edge technology.",
    wordType: "noun",
  },

  // ── Lesson 691–700 · Changes & Trends ────────────────────────────
  {
    id: 4691,
    subcategory: "Changes & Trends",
    folder: "changes-trends",
    word: "変化",
    reading: "へんか",
    meaning: "change",
    phrase: "大きな変化が起こる",
    phraseReading: "おおきな へんか が おこる",
    phraseMeaning: "a big change occurs",
    sentence: "社会は急速に変化している。",
    sentenceReading: "しゃかい は きゅうそく に へんか して いる。",
    sentenceMeaning: "Society is changing rapidly.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4692,
    subcategory: "Changes & Trends",
    folder: "changes-trends",
    word: "変動",
    reading: "へんどう",
    meaning: "fluctuation",
    phrase: "価格が変動する",
    phraseReading: "かかく が へんどう する",
    phraseMeaning: "prices fluctuate",
    sentence: "為替の変動で輸出が減った。",
    sentenceReading: "かわせ の へんどう で ゆしゅつ が へった。",
    sentenceMeaning: "Exports decreased due to currency fluctuations.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4693,
    subcategory: "Changes & Trends",
    folder: "changes-trends",
    word: "推移",
    reading: "すいい",
    meaning: "transition; development",
    phrase: "状況の推移を見守る",
    phraseReading: "じょうきょう の すいい を みまもる",
    phraseMeaning: "to watch the development of the situation",
    sentence: "売り上げの推移をグラフにまとめた。",
    sentenceReading: "うりあげ の すいい を ぐらふ に まとめた。",
    sentenceMeaning: "I summarized the sales trend in a graph.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4694,
    subcategory: "Changes & Trends",
    folder: "changes-trends",
    word: "拡大",
    reading: "かくだい",
    meaning: "expansion",
    phrase: "事業を拡大する",
    phraseReading: "じぎょう を かくだい する",
    phraseMeaning: "to expand a business",
    sentence: "会社は海外事業を拡大している。",
    sentenceReading: "かいしゃ は かいがい じぎょう を かくだい して いる。",
    sentenceMeaning: "The company is expanding its overseas business.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4695,
    subcategory: "Changes & Trends",
    folder: "changes-trends",
    word: "縮小",
    reading: "しゅくしょう",
    meaning: "reduction; contraction",
    phrase: "規模を縮小する",
    phraseReading: "きぼ を しゅくしょう する",
    phraseMeaning: "to reduce the scale",
    sentence: "不況で工場の規模を縮小した。",
    sentenceReading: "ふきょう で こうじょう の きぼ を しゅくしょう した。",
    sentenceMeaning: "Due to the recession, the factory reduced its scale.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4696,
    subcategory: "Changes & Trends",
    folder: "changes-trends",
    word: "増加",
    reading: "ぞうか",
    meaning: "increase",
    phrase: "人口が増加する",
    phraseReading: "じんこう が ぞうか する",
    phraseMeaning: "the population increases",
    sentence: "この町は観光客の増加で賑わっている。",
    sentenceReading: "この まち は かんこうきゃく の ぞうか で にぎわって いる。",
    sentenceMeaning: "This town is bustling due to an increase in tourists.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4697,
    subcategory: "Changes & Trends",
    folder: "changes-trends",
    word: "減少",
    reading: "げんしょう",
    meaning: "decrease",
    phrase: "売り上げが減少する",
    phraseReading: "うりあげ が げんしょう する",
    phraseMeaning: "sales decrease",
    sentence: "若者の人口が年々減少している。",
    sentenceReading: "わかもの の じんこう が ねんねん げんしょう して いる。",
    sentenceMeaning: "The population of young people is decreasing year by year.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4698,
    subcategory: "Changes & Trends",
    folder: "changes-trends",
    word: "急増",
    reading: "きゅうぞう",
    meaning: "rapid increase",
    phrase: "需要が急増する",
    phraseReading: "じゅよう が きゅうぞう する",
    phraseMeaning: "demand rapidly increases",
    sentence: "夏になると電力の需要が急増する。",
    sentenceReading: "なつ に なる と でんりょく の じゅよう が きゅうぞう する。",
    sentenceMeaning: "In summer, the demand for electricity rapidly increases.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4699,
    subcategory: "Changes & Trends",
    folder: "changes-trends",
    word: "浸透",
    reading: "しんとう",
    meaning: "penetration; permeation; spread",
    phrase: "考え方が浸透する",
    phraseReading: "かんがえかた が しんとう する",
    phraseMeaning: "a way of thinking spreads",
    sentence: "新しい習慣が社会に浸透してきた。",
    sentenceReading: "あたらしい しゅうかん が しゃかい に しんとう して きた。",
    sentenceMeaning: "New customs have come to spread through society.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4700,
    subcategory: "Changes & Trends",
    folder: "changes-trends",
    word: "衰退",
    reading: "すいたい",
    meaning: "decline",
    phrase: "産業が衰退する",
    phraseReading: "さんぎょう が すいたい する",
    phraseMeaning: "an industry declines",
    sentence: "この地域の伝統産業は衰退している。",
    sentenceReading: "この ちいき の でんとう さんぎょう は すいたい して いる。",
    sentenceMeaning: "The traditional industry in this region is declining.",
    wordType: "noun / suru-verb",
  },
