// ── Lesson 601–610 · Government & Politics ───────────────────────
{
  id: 4601,
  subcategory: "Government & Politics",
  folder: "government-politics",
  word: "政策",
  reading: "せいさく",
  meaning: "policy",
  phrase: "政策を打ち出す",
  phraseReading: "せいさく を うちだす",
  phraseMeaning: "to put forward a policy",
  sentence: "政府は新しい経済政策を打ち出した。",
  sentenceReading: "せいふ は あたらしい けいざい せいさく を うちだした。",
  sentenceMeaning: "The government put forward a new economic policy.",
  wordType: "noun",
},
{
  id: 4602,
  subcategory: "Government & Politics",
  folder: "government-politics",
  word: "制度",
  reading: "せいど",
  meaning: "system; institution",
  phrase: "年金制度",
  phraseReading: "ねんきん せいど",
  phraseMeaning: "pension system",
  sentence: "年金制度について国民の間で議論が続いている。",
  sentenceReading: "ねんきん せいど に ついて こくみん の あいだ で ぎろん が つづいて いる。",
  sentenceMeaning: "Debate about the pension system continues among the public.",
  wordType: "noun",
},
{
  id: 4603,
  subcategory: "Government & Politics",
  folder: "government-politics",
  word: "行政",
  reading: "ぎょうせい",
  meaning: "public administration",
  phrase: "行政の手続き",
  phraseReading: "ぎょうせい の てつづき",
  phraseMeaning: "administrative procedures",
  sentence: "行政の手続きが複雑で時間がかかった。",
  sentenceReading: "ぎょうせい の てつづき が ふくざつ で じかん が かかった。",
  sentenceMeaning: "The administrative procedures were complicated and took time.",
  wordType: "noun",
},
{
  id: 4604,
  subcategory: "Government & Politics",
  folder: "government-politics",
  word: "議会",
  reading: "ぎかい",
  meaning: "assembly; parliament",
  phrase: "議会で審議する",
  phraseReading: "ぎかい で しんぎ する",
  phraseMeaning: "to deliberate in the assembly",
  sentence: "その法案は議会で審議されている。",
  sentenceReading: "その ほうあん は ぎかい で しんぎ されて いる。",
  sentenceMeaning: "That bill is being deliberated in the assembly.",
  wordType: "noun",
},
{
  id: 4605,
  subcategory: "Government & Politics",
  folder: "government-politics",
  word: "選挙",
  reading: "せんきょ",
  meaning: "election",
  phrase: "選挙に立候補する",
  phraseReading: "せんきょ に りっこうほ する",
  phraseMeaning: "to run as a candidate in an election",
  sentence: "彼は市長選挙に立候補することを発表した。",
  sentenceReading: "かれ は しちょう せんきょ に りっこうほ する こと を はっぴょう した。",
  sentenceMeaning: "He announced that he would run in the mayoral election.",
  wordType: "noun / suru-verb",
},
{
  id: 4606,
  subcategory: "Government & Politics",
  folder: "government-politics",
  word: "投票",
  reading: "とうひょう",
  meaning: "voting",
  phrase: "投票に行く",
  phraseReading: "とうひょう に いく",
  phraseMeaning: "to go vote",
  sentence: "日曜日に投票に行くつもりだ。",
  sentenceReading: "にちようび に とうひょう に いく つもり だ。",
  sentenceMeaning: "I plan to go vote on Sunday.",
  wordType: "noun / suru-verb",
},
{
  id: 4607,
  subcategory: "Government & Politics",
  folder: "government-politics",
  word: "改革",
  reading: "かいかく",
  meaning: "reform",
  phrase: "教育改革を進める",
  phraseReading: "きょういく かいかく を すすめる",
  phraseMeaning: "to advance educational reform",
  sentence: "政府は教育改革を進めようとしている。",
  sentenceReading: "せいふ は きょういく かいかく を すすめよう と して いる。",
  sentenceMeaning: "The government is trying to advance educational reform.",
  wordType: "noun / suru-verb",
},
{
  id: 4608,
  subcategory: "Government & Politics",
  folder: "government-politics",
  word: "国民",
  reading: "こくみん",
  meaning: "citizens; people of a nation",
  phrase: "国民の声を聞く",
  phraseReading: "こくみん の こえ を きく",
  phraseMeaning: "to listen to the voice of the citizens",
  sentence: "政治家は国民の声をもっと聞くべきだ。",
  sentenceReading: "せいじか は こくみん の こえ を もっと きく べき だ。",
  sentenceMeaning: "Politicians should listen more to the voice of the citizens.",
  wordType: "noun",
},
{
  id: 4609,
  subcategory: "Government & Politics",
  folder: "government-politics",
  word: "財政",
  reading: "ざいせい",
  meaning: "public finance",
  phrase: "財政が悪化する",
  phraseReading: "ざいせい が あっか する",
  phraseMeaning: "for public finances to worsen",
  sentence: "国の財政が悪化していると報じられた。",
  sentenceReading: "くに の ざいせい が あっか して いる と ほうじられた。",
  sentenceMeaning: "It was reported that the nation's public finances are worsening.",
  wordType: "noun",
},
{
  id: 4610,
  subcategory: "Government & Politics",
  folder: "government-politics",
  word: "自治体",
  reading: "じちたい",
  meaning: "local government",
  phrase: "地方自治体",
  phraseReading: "ちほう じちたい",
  phraseMeaning: "local government (municipality)",
  sentence: "各地方自治体が独自の支援策を打ち出している。",
  sentenceReading: "かく ちほう じちたい が どくじ の しえんさく を うちだして いる。",
  sentenceMeaning: "Each local government is rolling out its own support measures.",
  wordType: "noun",
},

// ── Lesson 611–620 · Economy & Business Conditions ───────────────
{
  id: 4611,
  subcategory: "Economy & Business",
  folder: "economy-business",
  word: "景気",
  reading: "けいき",
  meaning: "economic conditions",
  phrase: "景気が回復する",
  phraseReading: "けいき が かいふく する",
  phraseMeaning: "for the economy to recover",
  sentence: "最近、景気が少しずつ回復している。",
  sentenceReading: "さいきん、けいき が すこしずつ かいふく して いる。",
  sentenceMeaning: "Recently, the economy has been gradually recovering.",
  wordType: "noun",
},
{
  id: 4612,
  subcategory: "Economy & Business",
  folder: "economy-business",
  word: "不況",
  reading: "ふきょう",
  meaning: "recession",
  phrase: "不況に陥る",
  phraseReading: "ふきょう に おちいる",
  phraseMeaning: "to fall into a recession",
  sentence: "その国は長い不況に陥っていた。",
  sentenceReading: "その くに は ながい ふきょう に おちいって いた。",
  sentenceMeaning: "That country had fallen into a long recession.",
  wordType: "noun",
},
{
  id: 4613,
  subcategory: "Economy & Business",
  folder: "economy-business",
  word: "物価",
  reading: "ぶっか",
  meaning: "commodity prices",
  phrase: "物価が上昇する",
  phraseReading: "ぶっか が じょうしょう する",
  phraseMeaning: "for commodity prices to rise",
  sentence: "最近、物価が上昇し続けている。",
  sentenceReading: "さいきん、ぶっか が じょうしょう しつづけて いる。",
  sentenceMeaning: "Prices have continued to rise recently.",
  wordType: "noun",
},
{
  id: 4614,
  subcategory: "Economy & Business",
  folder: "economy-business",
  word: "需要",
  reading: "じゅよう",
  meaning: "demand",
  phrase: "需要が高まる",
  phraseReading: "じゅよう が たかまる",
  phraseMeaning: "for demand to increase",
  sentence: "電気自動車の需要が高まっている。",
  sentenceReading: "でんき じどうしゃ の じゅよう が たかまって いる。",
  sentenceMeaning: "Demand for electric vehicles is increasing.",
  wordType: "noun",
},
{
  id: 4615,
  subcategory: "Economy & Business",
  folder: "economy-business",
  word: "供給",
  reading: "きょうきゅう",
  meaning: "supply",
  phrase: "供給が不足する",
  phraseReading: "きょうきゅう が ふそく する",
  phraseMeaning: "for supply to be insufficient",
  sentence: "部品の供給が不足して生産が滞った。",
  sentenceReading: "ぶひん の きょうきゅう が ふそく して せいさん が とどこおった。",
  sentenceMeaning: "The supply of parts was insufficient and production stalled.",
  wordType: "noun / suru-verb",
},
{
  id: 4616,
  subcategory: "Economy & Business",
  folder: "economy-business",
  word: "利益",
  reading: "りえき",
  meaning: "profit; benefit",
  phrase: "利益を上げる",
  phraseReading: "りえき を あげる",
  phraseMeaning: "to raise profits",
  sentence: "会社は今期、大きな利益を上げた。",
  sentenceReading: "かいしゃ は こんき、おおきな りえき を あげた。",
  sentenceMeaning: "The company posted a large profit this term.",
  wordType: "noun",
},
{
  id: 4617,
  subcategory: "Economy & Business",
  folder: "economy-business",
  word: "欠損",
  reading: "けっそん",
  meaning: "deficit; shortfall",
  phrase: "欠損を出す",
  phraseReading: "けっそん を だす",
  phraseMeaning: "to run a deficit",
  sentence: "その事業は今年度、大きな欠損を出した。",
  sentenceReading: "その じぎょう は こんねんど、おおきな けっそん を だした。",
  sentenceMeaning: "That business ran a large deficit this fiscal year.",
  wordType: "noun",
},
{
  id: 4618,
  subcategory: "Economy & Business",
  folder: "economy-business",
  word: "市場",
  reading: "しじょう",
  meaning: "market",
  phrase: "市場に参入する",
  phraseReading: "しじょう に さんにゅう する",
  phraseMeaning: "to enter the market",
  sentence: "新しい企業がその市場に参入した。",
  sentenceReading: "あたらしい きぎょう が その しじょう に さんにゅう した。",
  sentenceMeaning: "A new company entered that market.",
  wordType: "noun",
},
{
  id: 4619,
  subcategory: "Economy & Business",
  folder: "economy-business",
  word: "競争",
  reading: "きょうそう",
  meaning: "competition",
  phrase: "競争が激しい",
  phraseReading: "きょうそう が はげしい",
  phraseMeaning: "competition is fierce",
  sentence: "この業界は競争が激しい。",
  sentenceReading: "この ぎょうかい は きょうそう が はげしい。",
  sentenceMeaning: "Competition in this industry is fierce.",
  wordType: "noun / suru-verb",
},
{
  id: 4620,
  subcategory: "Economy & Business",
  folder: "economy-business",
  word: "成長率",
  reading: "せいちょうりつ",
  meaning: "growth rate",
  phrase: "経済成長率",
  phraseReading: "けいざい せいちょうりつ",
  phraseMeaning: "economic growth rate",
  sentence: "今年の経済成長率は予想より低かった。",
  sentenceReading: "こんねん の けいざい せいちょうりつ は よそう より ひくかった。",
  sentenceMeaning: "This year's economic growth rate was lower than expected.",
  wordType: "noun",
},

// ── Lesson 621–630 · Employment Conditions ────────────────────────
{
  id: 4621,
  subcategory: "Employment Conditions",
  folder: "employment-conditions",
  word: "雇用",
  reading: "こよう",
  meaning: "employment",
  phrase: "雇用を促進する",
  phraseReading: "こよう を そくしん する",
  phraseMeaning: "to promote employment",
  sentence: "政府は若者の雇用を促進する政策を発表した。",
  sentenceReading: "せいふ は わかもの の こよう を そくしん する せいさく を はっぴょう した。",
  sentenceMeaning: "The government announced a policy to promote employment for young people.",
  wordType: "noun / suru-verb",
},
{
  id: 4622,
  subcategory: "Employment Conditions",
  folder: "employment-conditions",
  word: "登用",
  reading: "とうよう",
  meaning: "appointment; promotion to a post",
  phrase: "人材を登用する",
  phraseReading: "じんざい を とうよう する",
  phraseMeaning: "to appoint talented personnel",
  sentence: "会社は若手社員を積極的に登用している。",
  sentenceReading: "かいしゃ は わかて しゃいん を せっきょくてき に とうよう して いる。",
  sentenceMeaning: "The company is actively appointing young employees to key posts.",
  wordType: "noun / suru-verb",
},
{
  id: 4623,
  subcategory: "Employment Conditions",
  folder: "employment-conditions",
  word: "解雇",
  reading: "かいこ",
  meaning: "dismissal",
  phrase: "解雇される",
  phraseReading: "かいこ される",
  phraseMeaning: "to be dismissed",
  sentence: "彼は突然、会社から解雇された。",
  sentenceReading: "かれ は とつぜん、かいしゃ から かいこ された。",
  sentenceMeaning: "He was suddenly dismissed from the company.",
  wordType: "noun / suru-verb",
},
{
  id: 4624,
  subcategory: "Employment Conditions",
  folder: "employment-conditions",
  word: "待遇",
  reading: "たいぐう",
  meaning: "treatment; employment conditions",
  phrase: "待遇を改善する",
  phraseReading: "たいぐう を かいぜん する",
  phraseMeaning: "to improve working conditions",
  sentence: "会社は社員の待遇を改善することにした。",
  sentenceReading: "かいしゃ は しゃいん の たいぐう を かいぜん する こと に した。",
  sentenceMeaning: "The company decided to improve its employees' working conditions.",
  wordType: "noun",
},
{
  id: 4625,
  subcategory: "Employment Conditions",
  folder: "employment-conditions",
  word: "給与",
  reading: "きゅうよ",
  meaning: "salary",
  phrase: "給与が上がる",
  phraseReading: "きゅうよ が あがる",
  phraseMeaning: "for one's salary to rise",
  sentence: "来年から給与が少し上がる予定だ。",
  sentenceReading: "らいねん から きゅうよ が すこし あがる よてい だ。",
  sentenceMeaning: "My salary is scheduled to rise a little starting next year.",
  wordType: "noun",
},
{
  id: 4626,
  subcategory: "Employment Conditions",
  folder: "employment-conditions",
  word: "手当",
  reading: "てあて",
  meaning: "allowance",
  phrase: "残業手当",
  phraseReading: "ざんぎょう てあて",
  phraseMeaning: "overtime allowance",
  sentence: "今月は残業手当が多くついた。",
  sentenceReading: "こんげつ は ざんぎょう てあて が おおく ついた。",
  sentenceMeaning: "I received a lot of overtime allowance this month.",
  wordType: "noun",
},
{
  id: 4627,
  subcategory: "Employment Conditions",
  folder: "employment-conditions",
  word: "勤務",
  reading: "きんむ",
  meaning: "work; service",
  phrase: "在宅勤務をする",
  phraseReading: "ざいたく きんむ を する",
  phraseMeaning: "to work from home",
  sentence: "この会社では週に二日、在宅勤務ができる。",
  sentenceReading: "この かいしゃ では しゅう に ふつか、ざいたく きんむ が できる。",
  sentenceMeaning: "At this company, you can work from home two days a week.",
  wordType: "noun / suru-verb",
},
{
  id: 4628,
  subcategory: "Employment Conditions",
  folder: "employment-conditions",
  word: "定年",
  reading: "ていねん",
  meaning: "retirement age",
  phrase: "定年を迎える",
  phraseReading: "ていねん を むかえる",
  phraseMeaning: "to reach retirement age",
  sentence: "父は来年、定年を迎える。",
  sentenceReading: "ちち は らいねん、ていねん を むかえる。",
  sentenceMeaning: "My father will reach retirement age next year.",
  wordType: "noun",
},
{
  id: 4629,
  subcategory: "Employment Conditions",
  folder: "employment-conditions",
  word: "人材",
  reading: "じんざい",
  meaning: "human resources; talent",
  phrase: "優秀な人材",
  phraseReading: "ゆうしゅう な じんざい",
  phraseMeaning: "excellent talent",
  sentence: "会社は優秀な人材を求めている。",
  sentenceReading: "かいしゃ は ゆうしゅう な じんざい を もとめて いる。",
  sentenceMeaning: "The company is seeking excellent talent.",
  wordType: "noun",
},
{
  id: 4630,
  subcategory: "Employment Conditions",
  folder: "employment-conditions",
  word: "労働力",
  reading: "ろうどうりょく",
  meaning: "labor force",
  phrase: "労働力が不足する",
  phraseReading: "ろうどうりょく が ふそく する",
  phraseMeaning: "for the labor force to be insufficient",
  sentence: "少子化により労働力が不足している。",
  sentenceReading: "しょうしか に より ろうどうりょく が ふそく して いる。",
  sentenceMeaning: "The labor force is insufficient due to the declining birth rate.",
  wordType: "noun",
},

// ── Lesson 631–640 · Environment & Sustainability ────────────────
{
  id: 4631,
  subcategory: "Environment & Sustainability",
  folder: "environment-sustainability",
  word: "温暖化",
  reading: "おんだんか",
  meaning: "global warming",
  phrase: "地球温暖化を防ぐ",
  phraseReading: "ちきゅう おんだんか を ふせぐ",
  phraseMeaning: "to prevent global warming",
  sentence: "私たちは地球温暖化を防ぐために行動しなければならない。",
  sentenceReading: "わたしたち は ちきゅう おんだんか を ふせぐ ため に こうどう しなければ ならない。",
  sentenceMeaning: "We must act to prevent global warming.",
  wordType: "noun / suru-verb",
},
{
  id: 4632,
  subcategory: "Environment & Sustainability",
  folder: "environment-sustainability",
  word: "排出",
  reading: "はいしゅつ",
  meaning: "emission; discharge",
  phrase: "二酸化炭素を排出する",
  phraseReading: "にさんかたんそ を はいしゅつ する",
  phraseMeaning: "to emit carbon dioxide",
  sentence: "工場は二酸化炭素を大量に排出していた。",
  sentenceReading: "こうじょう は にさんかたんそ を たいりょう に はいしゅつ して いた。",
  sentenceMeaning: "The factory was emitting large amounts of carbon dioxide.",
  wordType: "noun / suru-verb",
},
{
  id: 4633,
  subcategory: "Environment & Sustainability",
  folder: "environment-sustainability",
  word: "原料",
  reading: "げんりょう",
  meaning: "raw material",
  phrase: "天然の原料",
  phraseReading: "てんねん の げんりょう",
  phraseMeaning: "natural raw material",
  sentence: "この製品は天然の原料から作られている。",
  sentenceReading: "この せいひん は てんねん の げんりょう から つくられて いる。",
  sentenceMeaning: "This product is made from natural raw materials.",
  wordType: "noun",
},
{
  id: 4634,
  subcategory: "Environment & Sustainability",
  folder: "environment-sustainability",
  word: "再生可能",
  reading: "さいせいかのう",
  meaning: "renewable",
  phrase: "再生可能エネルギー",
  phraseReading: "さいせいかのう えねるぎー",
  phraseMeaning: "renewable energy",
  sentence: "再生可能エネルギーの利用が拡大している。",
  sentenceReading: "さいせいかのう えねるぎー の りよう が かくだい して いる。",
  sentenceMeaning: "The use of renewable energy is expanding.",
  wordType: "na-adjective",
},
{
  id: 4635,
  subcategory: "Environment & Sustainability",
  folder: "environment-sustainability",
  word: "生態系",
  reading: "せいたいけい",
  meaning: "ecosystem",
  phrase: "生態系を守る",
  phraseReading: "せいたいけい を まもる",
  phraseMeaning: "to protect the ecosystem",
  sentence: "森林の生態系を守る活動に参加した。",
  sentenceReading: "しんりん の せいたいけい を まもる かつどう に さんか した。",
  sentenceMeaning: "I took part in an activity to protect the forest ecosystem.",
  wordType: "noun",
},
{
  id: 4636,
  subcategory: "Environment & Sustainability",
  folder: "environment-sustainability",
  word: "汚染",
  reading: "おせん",
  meaning: "pollution",
  phrase: "大気汚染が進む",
  phraseReading: "たいき おせん が すすむ",
  phraseMeaning: "for air pollution to worsen",
  sentence: "この地域では大気汚染が進んでいる。",
  sentenceReading: "この ちいき では たいき おせん が すすんで いる。",
  sentenceMeaning: "Air pollution is worsening in this area.",
  wordType: "noun / suru-verb",
},
{
  id: 4637,
  subcategory: "Environment & Sustainability",
  folder: "environment-sustainability",
  word: "廃棄物",
  reading: "はいきぶつ",
  meaning: "waste material",
  phrase: "産業廃棄物を処理する",
  phraseReading: "さんぎょう はいきぶつ を しょり する",
  phraseMeaning: "to process industrial waste",
  sentence: "工場は産業廃棄物を適切に処理する必要がある。",
  sentenceReading: "こうじょう は さんぎょう はいきぶつ を てきせつ に しょり する ひつよう が ある。",
  sentenceMeaning: "Factories need to properly process industrial waste.",
  wordType: "noun",
},
{
  id: 4638,
  subcategory: "Environment & Sustainability",
  folder: "environment-sustainability",
  word: "削減",
  reading: "さくげん",
  meaning: "reduction",
  phrase: "コストを削減する",
  phraseReading: "こすと を さくげん する",
  phraseMeaning: "to reduce costs",
  sentence: "会社は経費を削減する方法を検討している。",
  sentenceReading: "かいしゃ は けいひ を さくげん する ほうほう を けんとう して いる。",
  sentenceMeaning: "The company is considering ways to reduce expenses.",
  wordType: "noun / suru-verb",
},
{
  id: 4639,
  subcategory: "Environment & Sustainability",
  folder: "environment-sustainability",
  word: "保護",
  reading: "ほご",
  meaning: "protection",
  phrase: "自然を保護する",
  phraseReading: "しぜん を ほご する",
  phraseMeaning: "to protect nature",
  sentence: "私たちには自然を保護する責任がある。",
  sentenceReading: "わたしたち に は しぜん を ほご する せきにん が ある。",
  sentenceMeaning: "We have a responsibility to protect nature.",
  wordType: "noun / suru-verb",
},
{
  id: 4640,
  subcategory: "Environment & Sustainability",
  folder: "environment-sustainability",
  word: "持続可能",
  reading: "じぞくかのう",
  meaning: "sustainable",
  phrase: "持続可能な社会",
  phraseReading: "じぞくかのう な しゃかい",
  phraseMeaning: "a sustainable society",
  sentence: "持続可能な社会を目指して取り組んでいる。",
  sentenceReading: "じぞくかのう な しゃかい を めざして とりくんで いる。",
  sentenceMeaning: "We are working toward a sustainable society.",
  wordType: "na-adjective",
},

// ── Lesson 641–650 · Crime & Public Safety ────────────────────────
{
  id: 4641,
  subcategory: "Crime & Public Safety",
  folder: "crime-safety",
  word: "犯罪",
  reading: "はんざい",
  meaning: "crime",
  phrase: "犯罪を防ぐ",
  phraseReading: "はんざい を ふせぐ",
  phraseMeaning: "to prevent crime",
  sentence: "地域で協力して犯罪を防ぐ取り組みが行われている。",
  sentenceReading: "ちいき で きょうりょく して はんざい を ふせぐ とりくみ が おこなわれて いる。",
  sentenceMeaning: "Efforts are being made in the community to cooperate and prevent crime.",
  wordType: "noun",
},
{
  id: 4642,
  subcategory: "Crime & Public Safety",
  folder: "crime-safety",
  word: "事件",
  reading: "じけん",
  meaning: "incident; criminal case",
  phrase: "事件が発生する",
  phraseReading: "じけん が はっせい する",
  phraseMeaning: "for an incident to occur",
  sentence: "昨夜、近所で事件が発生した。",
  sentenceReading: "さくや、きんじょ で じけん が はっせい した。",
  sentenceMeaning: "An incident occurred in the neighborhood last night.",
  wordType: "noun",
},
{
  id: 4643,
  subcategory: "Crime & Public Safety",
  folder: "crime-safety",
  word: "容疑者",
  reading: "ようぎしゃ",
  meaning: "suspect",
  phrase: "容疑者を捕まえる",
  phraseReading: "ようぎしゃ を つかまえる",
  phraseMeaning: "to catch a suspect",
  sentence: "警察はついに容疑者を捕まえた。",
  sentenceReading: "けいさつ は ついに ようぎしゃ を つかまえた。",
  sentenceMeaning: "The police finally caught the suspect.",
  wordType: "noun",
},
{
  id: 4644,
  subcategory: "Crime & Public Safety",
  folder: "crime-safety",
  word: "被害者",
  reading: "ひがいしゃ",
  meaning: "victim",
  phrase: "被害者を救助する",
  phraseReading: "ひがいしゃ を きゅうじょ する",
  phraseMeaning: "to rescue a victim",
  sentence: "消防隊が被害者を無事に救助した。",
  sentenceReading: "しょうぼうたい が ひがいしゃ を むじ に きゅうじょ した。",
  sentenceMeaning: "The fire brigade safely rescued the victim.",
  wordType: "noun",
},
{
  id: 4645,
  subcategory: "Crime & Public Safety",
  folder: "crime-safety",
  word: "逮捕",
  reading: "たいほ",
  meaning: "arrest",
  phrase: "犯人を逮捕する",
  phraseReading: "はんにん を たいほ する",
  phraseMeaning: "to arrest the culprit",
  sentence: "警察は数日後に犯人を逮捕した。",
  sentenceReading: "けいさつ は すうじつ ご に はんにん を たいほ した。",
  sentenceMeaning: "The police arrested the culprit a few days later.",
  wordType: "noun / suru-verb",
},
{
  id: 4646,
  subcategory: "Crime & Public Safety",
  folder: "crime-safety",
  word: "捜査",
  reading: "そうさ",
  meaning: "criminal investigation",
  phrase: "捜査を進める",
  phraseReading: "そうさ を すすめる",
  phraseMeaning: "to advance an investigation",
  sentence: "警察は事件の捜査を進めている。",
  sentenceReading: "けいさつ は じけん の そうさ を すすめて いる。",
  sentenceMeaning: "The police are advancing the investigation into the incident.",
  wordType: "noun / suru-verb",
},
{
  id: 4647,
  subcategory: "Crime & Public Safety",
  folder: "crime-safety",
  word: "証拠",
  reading: "しょうこ",
  meaning: "evidence",
  phrase: "証拠を見つける",
  phraseReading: "しょうこ を みつける",
  phraseMeaning: "to find evidence",
  sentence: "刑事は現場で重要な証拠を見つけた。",
  sentenceReading: "けいじ は げんば で じゅうよう な しょうこ を みつけた。",
  sentenceMeaning: "The detective found important evidence at the scene.",
  wordType: "noun",
},
{
  id: 4648,
  subcategory: "Crime & Public Safety",
  folder: "crime-safety",
  word: "警備",
  reading: "けいび",
  meaning: "security; guard",
  phrase: "警備を強化する",
  phraseReading: "けいび を きょうか する",
  phraseMeaning: "to strengthen security",
  sentence: "イベント会場では警備が強化されていた。",
  sentenceReading: "いべんと かいじょう では けいび が きょうか されて いた。",
  sentenceMeaning: "Security had been strengthened at the event venue.",
  wordType: "noun / suru-verb",
},
{
  id: 4649,
  subcategory: "Crime & Public Safety",
  folder: "crime-safety",
  word: "通報",
  reading: "つうほう",
  meaning: "report to authorities",
  phrase: "警察に通報する",
  phraseReading: "けいさつ に つうほう する",
  phraseMeaning: "to report to the police",
  sentence: "近所の人が異変に気づいて警察に通報した。",
  sentenceReading: "きんじょ の ひと が いへん に きづいて けいさつ に つうほう した。",
  sentenceMeaning: "A neighbor noticed something unusual and reported it to the police.",
  wordType: "noun / suru-verb",
},
{
  id: 4650,
  subcategory: "Crime & Public Safety",
  folder: "crime-safety",
  word: "不審者",
  reading: "ふしんしゃ",
  meaning: "suspicious person",
  phrase: "不審者を見かける",
  phraseReading: "ふしんしゃ を みかける",
  phraseMeaning: "to spot a suspicious person",
  sentence: "学校の周りで不審者を見かけたら連絡してください。",
  sentenceReading: "がっこう の まわり で ふしんしゃ を みかけたら れんらく して ください。",
  sentenceMeaning: "Please contact us if you spot a suspicious person around the school.",
  wordType: "noun",
},
