  // ── Lesson 501–510 · Advanced Weather & Climate ──
  {
    id: 4501,
    subcategory: "Weather & Climate",
    folder: "advanced-weather",
    word: "気候",
    reading: "きこう",
    meaning: "climate",
    phrase: "気候が変わる",
    phraseReading: "きこう が かわる",
    phraseMeaning: "the climate changes",
    sentence: "この地域は気候が温暖で過ごしやすい。",
    sentenceReading: "この ちいき は きこう が おんだん で すごしやすい。",
    sentenceMeaning: "This region has a mild climate and is comfortable to live in.",
    wordType: "noun",
  },
  {
    id: 4502,
    subcategory: "Weather & Climate",
    folder: "advanced-weather",
    word: "気圧",
    reading: "きあつ",
    meaning: "atmospheric pressure",
    phrase: "気圧が下がる",
    phraseReading: "きあつ が さがる",
    phraseMeaning: "the atmospheric pressure drops",
    sentence: "台風が近づくと気圧が急激に下がる。",
    sentenceReading: "たいふう が ちかづく と きあつ が きゅうげき に さがる。",
    sentenceMeaning: "When a typhoon approaches, the atmospheric pressure drops sharply.",
    wordType: "noun",
  },
  {
    id: 4503,
    subcategory: "Weather & Climate",
    folder: "advanced-weather",
    word: "寒波",
    reading: "かんぱ",
    meaning: "cold wave",
    phrase: "強い寒波",
    phraseReading: "つよい かんぱ",
    phraseMeaning: "a strong cold wave",
    sentence: "今週は強い寒波が日本列島を覆う見込みだ。",
    sentenceReading: "こんしゅう は つよい かんぱ が にほんれっとう を おおう みこみだ。",
    sentenceMeaning: "This week, a strong cold wave is expected to cover the Japanese archipelago.",
    wordType: "noun",
  },
  {
    id: 4504,
    subcategory: "Weather & Climate",
    folder: "advanced-weather",
    word: "熱帯夜",
    reading: "ねったいや",
    meaning: "sweltering night",
    phrase: "熱帯夜が続く",
    phraseReading: "ねったいや が つづく",
    phraseMeaning: "sweltering nights continue",
    sentence: "熱帯夜が続いて、なかなか寝付けない。",
    sentenceReading: "ねったいや が つづいて、なかなか ねつけない。",
    sentenceMeaning: "The sweltering nights continue, and I can hardly fall asleep.",
    wordType: "noun",
  },
  {
    id: 4505,
    subcategory: "Weather & Climate",
    folder: "advanced-weather",
    word: "日照",
    reading: "にっしょう",
    meaning: "sunlight; sunshine duration",
    phrase: "日照時間",
    phraseReading: "にっしょう じかん",
    phraseMeaning: "hours of sunshine",
    sentence: "今年の夏は日照時間が例年より長かった。",
    sentenceReading: "ことし の なつ は にっしょう じかん が れいねん より ながかった。",
    sentenceMeaning: "This summer's sunshine duration was longer than in an average year.",
    wordType: "noun",
  },
  {
    id: 4506,
    subcategory: "Weather & Climate",
    folder: "advanced-weather",
    word: "積雪",
    reading: "せきせつ",
    meaning: "accumulated snow",
    phrase: "積雪が増える",
    phraseReading: "せきせつ が ふえる",
    phraseMeaning: "accumulated snow increases",
    sentence: "山間部では例年より積雪が多い。",
    sentenceReading: "さんかんぶ で は れいねん より せきせつ が おおい。",
    sentenceMeaning: "In the mountainous areas, there is more accumulated snow than in an average year.",
    wordType: "noun",
  },
  {
    id: 4507,
    subcategory: "Weather & Climate",
    folder: "advanced-weather",
    word: "暴風",
    reading: "ぼうふう",
    meaning: "violent wind",
    phrase: "暴風警報",
    phraseReading: "ぼうふう けいほう",
    phraseMeaning: "violent wind warning",
    sentence: "暴風のため、電車が運転を見合わせている。",
    sentenceReading: "ぼうふう の ため、でんしゃ が うんてん を みあわせて いる。",
    sentenceMeaning: "Trains are suspending operations due to violent winds.",
    wordType: "noun",
  },
  {
    id: 4508,
    subcategory: "Weather & Climate",
    folder: "advanced-weather",
    word: "洪水",
    reading: "こうずい",
    meaning: "flood",
    phrase: "洪水が起きる",
    phraseReading: "こうずい が おきる",
    phraseMeaning: "a flood occurs",
    sentence: "大雨で川が氾濫し、洪水が発生した。",
    sentenceReading: "おおあめ で かわ が はんらん し、こうずい が はっせい した。",
    sentenceMeaning: "Due to the heavy rain, the river overflowed and a flood occurred.",
    wordType: "noun",
  },
  {
    id: 4509,
    subcategory: "Weather & Climate",
    folder: "advanced-weather",
    word: "乾燥",
    reading: "かんそう",
    meaning: "dryness",
    phrase: "空気が乾燥する",
    phraseReading: "くうき が かんそう する",
    phraseMeaning: "the air becomes dry",
    sentence: "冬は空気が乾燥するので、肌の手入れが欠かせない。",
    sentenceReading: "ふゆ は くうき が かんそう する の で、はだ の ていれ が かかせない。",
    sentenceMeaning: "In winter the air becomes dry, so skincare is essential.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4510,
    subcategory: "Weather & Climate",
    folder: "advanced-weather",
    word: "注意報",
    reading: "ちゅういほう",
    meaning: "weather advisory; warning bulletin",
    phrase: "大雨注意報",
    phraseReading: "おおあめ ちゅういほう",
    phraseMeaning: "heavy rain advisory",
    sentence: "強風のため、注意報が発表された。",
    sentenceReading: "きょうふう の ため、ちゅういほう が はっぴょう された。",
    sentenceMeaning: "A weather advisory was issued due to strong winds.",
    wordType: "noun",
  },

  // ── Lesson 511–520 · Social Etiquette & Consideration ──
  {
    id: 4511,
    subcategory: "Etiquette & Consideration",
    folder: "etiquette-consideration",
    word: "配慮",
    reading: "はいりょ",
    meaning: "consideration",
    phrase: "十分に配慮する",
    phraseReading: "じゅうぶん に はいりょ する",
    phraseMeaning: "to give thorough consideration",
    sentence: "高齢者にも配慮した設計になっている。",
    sentenceReading: "こうれいしゃ にも はいりょ した せっけい に なって いる。",
    sentenceMeaning: "The design also takes elderly people into consideration.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4512,
    subcategory: "Etiquette & Consideration",
    folder: "etiquette-consideration",
    word: "気遣い",
    reading: "きづかい",
    meaning: "thoughtfulness",
    phrase: "気遣いを見せる",
    phraseReading: "きづかい を みせる",
    phraseMeaning: "to show thoughtfulness",
    sentence: "彼女の細やかな気遣いに感謝している。",
    sentenceReading: "かのじょ の こまやか な きづかい に かんしゃ して いる。",
    sentenceMeaning: "I'm grateful for her thoughtful attention to detail.",
    wordType: "noun",
  },
  {
    id: 4513,
    subcategory: "Etiquette & Consideration",
    folder: "etiquette-consideration",
    word: "謙遜",
    reading: "けんそん",
    meaning: "modesty; humility",
    phrase: "謙遜して言う",
    phraseReading: "けんそん して いう",
    phraseMeaning: "to say something modestly",
    sentence: "彼は成功しても謙遜する態度を崩さない。",
    sentenceReading: "かれ は せいこう しても けんそん する たいど を くずさない。",
    sentenceMeaning: "Even when he succeeds, he doesn't lose his modest attitude.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4514,
    subcategory: "Etiquette & Consideration",
    folder: "etiquette-consideration",
    word: "作法",
    reading: "さほう",
    meaning: "manners; etiquette",
    phrase: "茶道の作法",
    phraseReading: "さどう の さほう",
    phraseMeaning: "the etiquette of tea ceremony",
    sentence: "日本には食事の作法が細かく決まっている。",
    sentenceReading: "にほん に は しょくじ の さほう が こまかく きまって いる。",
    sentenceMeaning: "In Japan, dining etiquette is defined in detail.",
    wordType: "noun",
  },
  {
    id: 4515,
    subcategory: "Etiquette & Consideration",
    folder: "etiquette-consideration",
    word: "常識",
    reading: "じょうしき",
    meaning: "common sense",
    phrase: "常識がない",
    phraseReading: "じょうしき が ない",
    phraseMeaning: "to lack common sense",
    sentence: "それは社会人としての常識だと思う。",
    sentenceReading: "それ は しゃかいじん として の じょうしきだ と おもう。",
    sentenceMeaning: "I think that's common sense as a member of society.",
    wordType: "noun",
  },
  {
    id: 4516,
    subcategory: "Etiquette & Consideration",
    folder: "etiquette-consideration",
    word: "失礼",
    reading: "しつれい",
    meaning: "rudeness; discourtesy",
    phrase: "失礼な態度",
    phraseReading: "しつれい な たいど",
    phraseMeaning: "a rude attitude",
    sentence: "話の途中で席を立つのは失礼にあたる。",
    sentenceReading: "はなし の とちゅう で せき を たつ の は しつれい に あたる。",
    sentenceMeaning: "Leaving your seat in the middle of a conversation is considered rude.",
    wordType: "noun / na-adjective",
  },
  {
    id: 4517,
    subcategory: "Etiquette & Consideration",
    folder: "etiquette-consideration",
    word: "控える",
    reading: "ひかえる",
    meaning: "to refrain from",
    phrase: "飲酒を控える",
    phraseReading: "いんしゅ を ひかえる",
    phraseMeaning: "to refrain from drinking alcohol",
    sentence: "医者に塩分を控えるよう言われた。",
    sentenceReading: "いしゃ に えんぶん を ひかえる よう いわれた。",
    sentenceMeaning: "I was told by the doctor to cut back on salt.",
    wordType: "verb (group 2)",
  },
  {
    id: 4518,
    subcategory: "Etiquette & Consideration",
    folder: "etiquette-consideration",
    word: "譲る",
    reading: "ゆずる",
    meaning: "to yield; give way",
    phrase: "席を譲る",
    phraseReading: "せき を ゆずる",
    phraseMeaning: "to give up one's seat",
    sentence: "電車でお年寄りに席を譲った。",
    sentenceReading: "でんしゃ で おとしより に せき を ゆずった。",
    sentenceMeaning: "I gave up my seat to an elderly person on the train.",
    wordType: "verb (group 1)",
  },
  {
    id: 4519,
    subcategory: "Etiquette & Consideration",
    folder: "etiquette-consideration",
    word: "慎む",
    reading: "つつしむ",
    meaning: "to be discreet; refrain",
    phrase: "言動を慎む",
    phraseReading: "げんどう を つつしむ",
    phraseMeaning: "to be discreet in one's words and actions",
    sentence: "公の場では言葉を慎むべきだ。",
    sentenceReading: "おおやけ の ば で は ことば を つつしむ べきだ。",
    sentenceMeaning: "One should be discreet with one's words in public.",
    wordType: "verb (group 1)",
  },
  {
    id: 4520,
    subcategory: "Etiquette & Consideration",
    folder: "etiquette-consideration",
    word: "わきまえる",
    reading: "わきまえる",
    meaning: "to understand one's position",
    phrase: "立場をわきまえる",
    phraseReading: "たちば を わきまえる",
    phraseMeaning: "to know one's place",
    sentence: "目上の人には礼儀をわきまえて接するべきだ。",
    sentenceReading: "めうえ の ひと に は れいぎ を わきまえて せっする べきだ。",
    sentenceMeaning: "One should behave with proper manners toward one's superiors.",
    wordType: "verb (group 2)",
  },

  // ── Lesson 521–530 · Workplace Communication ──
  {
    id: 4521,
    subcategory: "Workplace Communication",
    folder: "workplace-communication",
    word: "配布",
    reading: "はいふ",
    meaning: "distribution; handout",
    phrase: "資料を配布する",
    phraseReading: "しりょう を はいふ する",
    phraseMeaning: "to distribute materials",
    sentence: "会議の前に資料を配布しておいた。",
    sentenceReading: "かいぎ の まえ に しりょう を はいふ して おいた。",
    sentenceMeaning: "I distributed the materials before the meeting.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4522,
    subcategory: "Workplace Communication",
    folder: "workplace-communication",
    word: "周知",
    reading: "しゅうち",
    meaning: "making something widely known",
    phrase: "社内に周知する",
    phraseReading: "しゃない に しゅうち する",
    phraseMeaning: "to make widely known within the company",
    sentence: "新しい規則を全員に周知しておいてください。",
    sentenceReading: "あたらしい きそく を ぜんいん に しゅうち して おいて ください。",
    sentenceMeaning: "Please make sure everyone is informed of the new rules.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4523,
    subcategory: "Workplace Communication",
    folder: "workplace-communication",
    word: "確認事項",
    reading: "かくにんじこう",
    meaning: "points requiring confirmation",
    phrase: "確認事項をまとめる",
    phraseReading: "かくにんじこう を まとめる",
    phraseMeaning: "to compile the points needing confirmation",
    sentence: "会議の最後に確認事項を共有した。",
    sentenceReading: "かいぎ の さいご に かくにんじこう を きょうゆう した。",
    sentenceMeaning: "At the end of the meeting, we shared the points that needed confirmation.",
    wordType: "noun",
  },
  {
    id: 4524,
    subcategory: "Workplace Communication",
    folder: "workplace-communication",
    word: "引き継ぎ",
    reading: "ひきつぎ",
    meaning: "handover",
    phrase: "業務の引き継ぎ",
    phraseReading: "ぎょうむ の ひきつぎ",
    phraseMeaning: "handover of duties",
    sentence: "退職前に後任者へ引き継ぎを行った。",
    sentenceReading: "たいしょく まえ に こうにんしゃ へ ひきつぎ を おこなった。",
    sentenceMeaning: "I did the handover to my successor before retiring.",
    wordType: "noun",
  },
  {
    id: 4525,
    subcategory: "Workplace Communication",
    folder: "workplace-communication",
    word: "進捗",
    reading: "しんちょく",
    meaning: "progress",
    phrase: "進捗を報告する",
    phraseReading: "しんちょく を ほうこく する",
    phraseMeaning: "to report on progress",
    sentence: "毎週プロジェクトの進捗を確認している。",
    sentenceReading: "まいしゅう ぷろじぇくと の しんちょく を かくにん して いる。",
    sentenceMeaning: "I check the project's progress every week.",
    wordType: "noun",
  },
  {
    id: 4526,
    subcategory: "Workplace Communication",
    folder: "workplace-communication",
    word: "調整",
    reading: "ちょうせい",
    meaning: "coordination; adjustment",
    phrase: "日程を調整する",
    phraseReading: "にってい を ちょうせい する",
    phraseMeaning: "to adjust the schedule",
    sentence: "会議の時間を調整してもらえますか。",
    sentenceReading: "かいぎ の じかん を ちょうせい して もらえます か。",
    sentenceMeaning: "Could you adjust the meeting time?",
    wordType: "noun / suru-verb",
  },
  {
    id: 4527,
    subcategory: "Workplace Communication",
    folder: "workplace-communication",
    word: "回覧",
    reading: "かいらん",
    meaning: "circulation of a document",
    phrase: "回覧板を回す",
    phraseReading: "かいらんばん を まわす",
    phraseMeaning: "to pass around the circulation notice board",
    sentence: "この文書は部署内で回覧してください。",
    sentenceReading: "この ぶんしょ は ぶしょない で かいらん して ください。",
    sentenceMeaning: "Please circulate this document within the department.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4528,
    subcategory: "Workplace Communication",
    folder: "workplace-communication",
    word: "承認",
    reading: "しょうにん",
    meaning: "approval",
    phrase: "上司の承認を得る",
    phraseReading: "じょうし の しょうにん を える",
    phraseMeaning: "to get the boss's approval",
    sentence: "この計画は部長の承認を得てから実行する。",
    sentenceReading: "この けいかく は ぶちょう の しょうにん を えて から じっこう する。",
    sentenceMeaning: "This plan will be carried out after obtaining the department head's approval.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4529,
    subcategory: "Workplace Communication",
    folder: "workplace-communication",
    word: "了承",
    reading: "りょうしょう",
    meaning: "acknowledgment; consent",
    phrase: "了承を得る",
    phraseReading: "りょうしょう を える",
    phraseMeaning: "to obtain consent",
    sentence: "出張の件については上司の了承を得ています。",
    sentenceReading: "しゅっちょう の けん について は じょうし の りょうしょう を えて います。",
    sentenceMeaning: "Regarding the business trip, I have obtained my boss's consent.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4530,
    subcategory: "Workplace Communication",
    folder: "workplace-communication",
    word: "催促",
    reading: "さいそく",
    meaning: "reminder; urging",
    phrase: "支払いを催促する",
    phraseReading: "しはらい を さいそく する",
    phraseMeaning: "to press for payment",
    sentence: "返事がないので、もう一度催促のメールを送った。",
    sentenceReading: "へんじ が ない の で、もう いちど さいそく の めーる を おくった。",
    sentenceMeaning: "Since there was no reply, I sent another reminder email.",
    wordType: "noun / suru-verb",
  },

  // ── Lesson 531–540 · Decisions & Problem Solving ──
  {
    id: 4531,
    subcategory: "Decisions & Problem Solving",
    folder: "decisions-problems",
    word: "判断",
    reading: "はんだん",
    meaning: "judgment",
    phrase: "冷静に判断する",
    phraseReading: "れいせい に はんだん する",
    phraseMeaning: "to judge calmly",
    sentence: "状況を見て自分で判断してください。",
    sentenceReading: "じょうきょう を みて じぶん で はんだん して ください。",
    sentenceMeaning: "Please assess the situation and make your own judgment.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4532,
    subcategory: "Decisions & Problem Solving",
    folder: "decisions-problems",
    word: "決断",
    reading: "けつだん",
    meaning: "decision",
    phrase: "決断を下す",
    phraseReading: "けつだん を くだす",
    phraseMeaning: "to make a decision",
    sentence: "転職するかどうか、大きな決断を迫られている。",
    sentenceReading: "てんしょく する か どう か、おおきな けつだん を せまられて いる。",
    sentenceMeaning: "I'm being pressed to make a big decision about whether to change jobs.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4533,
    subcategory: "Decisions & Problem Solving",
    folder: "decisions-problems",
    word: "検討",
    reading: "けんとう",
    meaning: "consideration; examination",
    phrase: "案を検討する",
    phraseReading: "あん を けんとう する",
    phraseMeaning: "to examine a proposal",
    sentence: "いただいたご提案は社内で検討させていただきます。",
    sentenceReading: "いただいた ご ていあん は しゃない で けんとう させて いただきます。",
    sentenceMeaning: "We will consider the proposal you gave us within the company.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4534,
    subcategory: "Decisions & Problem Solving",
    folder: "decisions-problems",
    word: "対処",
    reading: "たいしょ",
    meaning: "handling; dealing with",
    phrase: "問題に対処する",
    phraseReading: "もんだい に たいしょ する",
    phraseMeaning: "to deal with a problem",
    sentence: "トラブルには冷静に対処するべきだ。",
    sentenceReading: "とらぶる に は れいせい に たいしょ する べきだ。",
    sentenceMeaning: "One should handle trouble calmly.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4535,
    subcategory: "Decisions & Problem Solving",
    folder: "decisions-problems",
    word: "解決",
    reading: "かいけつ",
    meaning: "solution; resolution",
    phrase: "問題を解決する",
    phraseReading: "もんだい を かいけつ する",
    phraseMeaning: "to solve a problem",
    sentence: "この課題はチーム全員で解決したい。",
    sentenceReading: "この かだい は ちーむ ぜんいん で かいけつ したい。",
    sentenceMeaning: "I want the whole team to solve this issue together.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4536,
    subcategory: "Decisions & Problem Solving",
    folder: "decisions-problems",
    word: "改善",
    reading: "かいぜん",
    meaning: "improvement",
    phrase: "状況を改善する",
    phraseReading: "じょうきょう を かいぜん する",
    phraseMeaning: "to improve the situation",
    sentence: "作業の効率を改善するために手順を見直した。",
    sentenceReading: "さぎょう の こうりつ を かいぜん する ため に てじゅん を みなおした。",
    sentenceMeaning: "I reviewed the procedure in order to improve work efficiency.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4537,
    subcategory: "Decisions & Problem Solving",
    folder: "decisions-problems",
    word: "工夫",
    reading: "くふう",
    meaning: "ingenuity; creative effort",
    phrase: "工夫を重ねる",
    phraseReading: "くふう を かさねる",
    phraseMeaning: "to make repeated creative efforts",
    sentence: "限られた予算の中でいろいろな工夫をした。",
    sentenceReading: "かぎられた よさん の なか で いろいろ な くふう を した。",
    sentenceMeaning: "I made various creative efforts within a limited budget.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4538,
    subcategory: "Decisions & Problem Solving",
    folder: "decisions-problems",
    word: "方針",
    reading: "ほうしん",
    meaning: "policy; course of action",
    phrase: "方針を決める",
    phraseReading: "ほうしん を きめる",
    phraseMeaning: "to decide on a policy",
    sentence: "会社の今後の方針が発表された。",
    sentenceReading: "かいしゃ の こんご の ほうしん が はっぴょう された。",
    sentenceMeaning: "The company's future policy was announced.",
    wordType: "noun",
  },
  {
    id: 4539,
    subcategory: "Decisions & Problem Solving",
    folder: "decisions-problems",
    word: "手段",
    reading: "しゅだん",
    meaning: "means; method",
    phrase: "目的のための手段",
    phraseReading: "もくてき の ため の しゅだん",
    phraseMeaning: "a means to an end",
    sentence: "目的を達成するためにあらゆる手段を試した。",
    sentenceReading: "もくてき を たっせい する ため に あらゆる しゅだん を ためした。",
    sentenceMeaning: "I tried every means to achieve my goal.",
    wordType: "noun",
  },
  {
    id: 4540,
    subcategory: "Decisions & Problem Solving",
    folder: "decisions-problems",
    word: "妥当",
    reading: "だとう",
    meaning: "reasonable; appropriate",
    phrase: "妥当な価格",
    phraseReading: "だとう な かかく",
    phraseMeaning: "a reasonable price",
    sentence: "この提案は現実的で妥当だと思う。",
    sentenceReading: "この ていあん は げんじつてき で だとうだ と おもう。",
    sentenceMeaning: "I think this proposal is realistic and reasonable.",
    wordType: "na-adjective",
  },

  // ── Lesson 541–550 · Quality & Manufacturing ──
  {
    id: 4541,
    subcategory: "Quality & Manufacturing",
    folder: "quality-manufacturing",
    word: "品質",
    reading: "ひんしつ",
    meaning: "quality",
    phrase: "品質を保つ",
    phraseReading: "ひんしつ を たもつ",
    phraseMeaning: "to maintain quality",
    sentence: "この工場は製品の品質にこだわっている。",
    sentenceReading: "この こうじょう は せいひん の ひんしつ に こだわって いる。",
    sentenceMeaning: "This factory is particular about the quality of its products.",
    wordType: "noun",
  },
  {
    id: 4542,
    subcategory: "Quality & Manufacturing",
    folder: "quality-manufacturing",
    word: "不良",
    reading: "ふりょう",
    meaning: "defect; faulty condition",
    phrase: "不良品",
    phraseReading: "ふりょうひん",
    phraseMeaning: "defective product",
    sentence: "検査で不良が見つかった製品は出荷しない。",
    sentenceReading: "けんさ で ふりょう が みつかった せいひん は しゅっか しない。",
    sentenceMeaning: "Products found to be defective during inspection are not shipped.",
    wordType: "noun",
  },
  {
    id: 4543,
    subcategory: "Quality & Manufacturing",
    folder: "quality-manufacturing",
    word: "欠陥",
    reading: "けっかん",
    meaning: "defect; flaw",
    phrase: "欠陥が見つかる",
    phraseReading: "けっかん が みつかる",
    phraseMeaning: "a defect is found",
    sentence: "この製品には設計上の欠陥があった。",
    sentenceReading: "この せいひん に は せっけいじょう の けっかん が あった。",
    sentenceMeaning: "This product had a design flaw.",
    wordType: "noun",
  },
  {
    id: 4544,
    subcategory: "Quality & Manufacturing",
    folder: "quality-manufacturing",
    word: "耐久性",
    reading: "たいきゅうせい",
    meaning: "durability",
    phrase: "耐久性が高い",
    phraseReading: "たいきゅうせい が たかい",
    phraseMeaning: "high durability",
    sentence: "この素材は耐久性が高く、長く使える。",
    sentenceReading: "この そざい は たいきゅうせい が たかく、ながく つかえる。",
    sentenceMeaning: "This material has high durability and can be used for a long time.",
    wordType: "noun",
  },
  {
    id: 4545,
    subcategory: "Quality & Manufacturing",
    folder: "quality-manufacturing",
    word: "精度",
    reading: "せいど",
    meaning: "precision; accuracy",
    phrase: "精度を上げる",
    phraseReading: "せいど を あげる",
    phraseMeaning: "to increase precision",
    sentence: "新しい機械で加工の精度が上がった。",
    sentenceReading: "あたらしい きかい で かこう の せいど が あがった。",
    sentenceMeaning: "With the new machine, the precision of the processing improved.",
    wordType: "noun",
  },
  {
    id: 4546,
    subcategory: "Quality & Manufacturing",
    folder: "quality-manufacturing",
    word: "寸法",
    reading: "すんぽう",
    meaning: "dimensions",
    phrase: "寸法を測る",
    phraseReading: "すんぽう を はかる",
    phraseMeaning: "to measure dimensions",
    sentence: "家具を注文する前に部屋の寸法を測った。",
    sentenceReading: "かぐ を ちゅうもん する まえ に へや の すんぽう を はかった。",
    sentenceMeaning: "I measured the room's dimensions before ordering furniture.",
    wordType: "noun",
  },
  {
    id: 4547,
    subcategory: "Quality & Manufacturing",
    folder: "quality-manufacturing",
    word: "誤差",
    reading: "ごさ",
    meaning: "error; margin of error",
    phrase: "誤差が生じる",
    phraseReading: "ごさ が しょうじる",
    phraseMeaning: "an error arises",
    sentence: "測定には多少の誤差が生じるものだ。",
    sentenceReading: "そくてい に は たしょう の ごさ が しょうじる もの だ。",
    sentenceMeaning: "Some margin of error is bound to arise in measurement.",
    wordType: "noun",
  },
  {
    id: 4548,
    subcategory: "Quality & Manufacturing",
    folder: "quality-manufacturing",
    word: "仕様",
    reading: "しよう",
    meaning: "specification",
    phrase: "仕様を確認する",
    phraseReading: "しよう を かくにん する",
    phraseMeaning: "to check the specifications",
    sentence: "発注前に製品の仕様を確認しておこう。",
    sentenceReading: "はっちゅう まえ に せいひん の しよう を かくにん して おこう。",
    sentenceMeaning: "Let's check the product specifications before placing the order.",
    wordType: "noun",
  },
  {
    id: 4549,
    subcategory: "Quality & Manufacturing",
    folder: "quality-manufacturing",
    word: "試作",
    reading: "しさく",
    meaning: "prototype production",
    phrase: "試作品を作る",
    phraseReading: "しさくひん を つくる",
    phraseMeaning: "to make a prototype",
    sentence: "新製品の試作を何度も繰り返した。",
    sentenceReading: "しんせいひん の しさく を なんども くりかえした。",
    sentenceMeaning: "We repeated the prototyping of the new product many times.",
    wordType: "noun / suru-verb",
  },
  {
    id: 4550,
    subcategory: "Quality & Manufacturing",
    folder: "quality-manufacturing",
    word: "検品",
    reading: "けんぴん",
    meaning: "product inspection",
    phrase: "検品を行う",
    phraseReading: "けんぴん を おこなう",
    phraseMeaning: "to carry out product inspection",
    sentence: "出荷前に必ず検品を行っている。",
    sentenceReading: "しゅっか まえ に かならず けんぴん を おこなって いる。",
    sentenceMeaning: "We always carry out product inspection before shipping.",
    wordType: "noun / suru-verb",
  },
