/**
 * Builds the stroke-order data for every kanji used in vocabulary words.
 *
 *   node scripts/kanjiStrokes/generateKanjiStrokes.mjs [path/to/kanjivg]
 *
 * Source: a local checkout of KanjiVG (https://github.com/KanjiVG/kanjivg),
 * default ../kanjivg next to this repo, or the KANJIVG_DIR env variable:
 *
 *   git clone --depth 1 https://github.com/KanjiVG/kanjivg ..\kanjivg
 *
 * Reads the words from the vocabulary seed files (the same files
 * scripts/levels/generateLevels.mjs reads), takes each kanji's strokes in
 * stroke order (the -s1, -s2 … path ids), and writes
 *   src/components/KanjiStrokes/kanjiStrokes.data.ts
 * Re-run after adding vocabulary; kanjiStrokes.test.ts fails until you do.
 *
 * KanjiVG © Ulrich Apel, CC BY-SA 3.0. The generated file is a derivative
 * and carries the same licence (see KANJIVG-LICENSE.md).
 */
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..", "..");
const kanjivg = resolve(process.argv[2] ?? process.env.KANJIVG_DIR ?? join(root, "..", "kanjivg"));
const out = join(root, "src/components/KanjiStrokes/kanjiStrokes.data.ts");

const SEED_FILES = [
  "src/data/vocabulary.ts",
  "src/data/vocabularyCore2000Seeds.ts",
  "src/data/n3/vocabularyN3Seeds.ts",
];
const KANJI = /[\u3400-\u4dbf\u4e00-\u9fff々]/u;

if (!existsSync(join(kanjivg, "kanji"))) {
  console.error(`KanjiVG not found at ${kanjivg}\n` +
    "Clone it first:  git clone --depth 1 https://github.com/KanjiVG/kanjivg ../kanjivg");
  process.exit(1);
}

// 1. Every kanji in every vocabulary word.
const chars = new Set();
for (const file of SEED_FILES) {
  const text = readFileSync(join(root, file), "utf8");
  for (const m of text.matchAll(/\bword:\s*"([^"]+)"/g)) {
    for (const ch of m[1]) if (KANJI.test(ch)) chars.add(ch);
  }
}

// 2. Strokes, in stroke order, from each kanji's own SVG.
const strokes = {};
const missing = [];
for (const ch of [...chars].sort((a, b) => a.codePointAt(0) - b.codePointAt(0))) {
  const file = join(kanjivg, "kanji", `${ch.codePointAt(0).toString(16).padStart(5, "0")}.svg`);
  if (!existsSync(file)) {
    missing.push(ch);
    continue;
  }
  const svg = readFileSync(file, "utf8");
  const paths = [...svg.matchAll(/<path\s+id="kvg:[0-9a-f]+-s(\d+)"[^>]*?\sd="([^"]+)"/g)]
    .map((m) => ({ n: Number(m[1]), d: m[2].replace(/\s+/g, " ").trim() }))
    .sort((a, b) => a.n - b.n);
  if (paths.length === 0) {
    missing.push(ch);
    continue;
  }
  strokes[ch] = paths.map((p) => p.d);
}

let version = "unknown";
try {
  version = execFileSync("git", ["-C", kanjivg, "log", "-1", "--format=%h %cd", "--date=short"], {
    encoding: "utf8",
  }).trim();
} catch {
  // not a git checkout — fine
}

// 3. Write the data module.
const lines = [
  "/*",
  " * GENERATED by scripts/kanjiStrokes/generateKanjiStrokes.mjs — do not edit by hand.",
  " *",
  " * Stroke-order data: KanjiVG (https://kanjivg.tagaini.net), © Ulrich Apel,",
  " * licensed CC BY-SA 3.0. This file is a derivative of KanjiVG and is shared",
  " * under the same licence (see KANJIVG-LICENSE.md).",
  " */",
  "",
  `export const KANJIVG_VERSION = ${JSON.stringify(version)};`,
  "",
  "/** Each kanji's strokes as SVG path data (109×109 grid), in stroke order. */",
  "export const KANJI_STROKES: Readonly<Record<string, readonly string[]>> = {",
  ...Object.entries(strokes).map(([ch, ds]) => `  ${JSON.stringify(ch)}: ${JSON.stringify(ds)},`),
  "};",
  "",
];
writeFileSync(out, lines.join("\n"));

const total = Object.values(strokes).reduce((n, s) => n + s.length, 0);
console.log(`kanji: ${Object.keys(strokes).length}  strokes: ${total}  KanjiVG: ${version}`);
if (missing.length) {
  console.warn(`missing from KanjiVG (${missing.length}): ${missing.join("")}`);
  process.exitCode = 1;
}
console.log(`wrote ${out}`);
