import type { ComponentType } from "react";
import { SVG_ART } from "../../../components/Illustration/svgArt";
import {
  AirConditioner,
  BathStool,
  Bench,
  Blackboard,
  CoinLocker,
  Crosswalk,
  CurveMirror,
  CuttingBoard,
  ElectricFan,
  EmergencyExit,
  Escalator,
  Faucet,
  GasStove,
  Guardrail,
  HandStrap,
  Hanger,
  Intercom,
  InsectScreen,
  IronBar,
  Kotatsu,
  Ladle,
  LaundryPole,
  LightSwitch,
  LuggageRack,
  Manhole,
  Microwave,
  NoticeBoard,
  Noren,
  Outlet,
  ParcelLocker,
  Pot,
  RailroadCrossing,
  Randoseru,
  Remote,
  Seesaw,
  Shoji,
  ShoppingBasket,
  Slide,
  Stairs,
  Streetlight,
  Swing,
  TactilePaving,
  Tatami,
  Thermometer,
  TicketGate,
  TicketMachine,
  TrafficCone,
  UmbrellaStand,
  UtilityPole,
  VendingMachine,
  WashBowl,
  Zabuton,
} from "./everydayArt";

/** Drawings made for Everyday Japanese, by the id used as `svg:<id>`. */
export const EVERYDAY_ART: Readonly<Record<string, ComponentType>> = {
  "air-conditioner": AirConditioner,
  "bath-stool": BathStool,
  bench: Bench,
  blackboard: Blackboard,
  "coin-locker": CoinLocker,
  crosswalk: Crosswalk,
  "curve-mirror": CurveMirror,
  "cutting-board": CuttingBoard,
  "electric-fan": ElectricFan,
  "emergency-exit": EmergencyExit,
  escalator: Escalator,
  faucet: Faucet,
  "gas-stove": GasStove,
  guardrail: Guardrail,
  "hand-strap": HandStrap,
  hanger: Hanger,
  intercom: Intercom,
  "insect-screen": InsectScreen,
  "iron-bar": IronBar,
  kotatsu: Kotatsu,
  ladle: Ladle,
  "laundry-pole": LaundryPole,
  "light-switch": LightSwitch,
  "luggage-rack": LuggageRack,
  manhole: Manhole,
  microwave: Microwave,
  "notice-board": NoticeBoard,
  noren: Noren,
  outlet: Outlet,
  "parcel-locker": ParcelLocker,
  pot: Pot,
  "railroad-crossing": RailroadCrossing,
  randoseru: Randoseru,
  remote: Remote,
  seesaw: Seesaw,
  shoji: Shoji,
  "shopping-basket": ShoppingBasket,
  slide: Slide,
  stairs: Stairs,
  streetlight: Streetlight,
  swing: Swing,
  "tactile-paving": TactilePaving,
  tatami: Tatami,
  thermometer: Thermometer,
  "ticket-gate": TicketGate,
  "ticket-machine": TicketMachine,
  "traffic-cone": TrafficCone,
  "umbrella-stand": UmbrellaStand,
  "utility-pole": UtilityPole,
  "vending-machine": VendingMachine,
  "wash-bowl": WashBowl,
  zabuton: Zabuton,
};

/**
 * Resolve `svg:<id>`: this trainer's own drawings first, then the player's
 * shared Illustration set (fridge, washer, ventfan, ricecooker, …) so those
 * drawings are reused rather than redrawn.
 */
export function resolveArt(id: string): ComponentType | undefined {
  return EVERYDAY_ART[id] ?? SVG_ART[id];
}
