/**
 * Tags every vocabulary item with its real JLPT level and builds the
 * level-pure playlist lessons used for the YouTube playlists.
 *
 *   node scripts/levels/generateLevels.mjs
 *
 * Inputs
 *   scripts/levels/jlptWordLevels.tsv     word|reading|level (committed list)
 *   src/data/vocabulary.ts                N2 course seeds (4001–4750) + N1_VOCAB_IDS
 *   src/data/vocabularyCore2000Seeds.ts   Core 2000 seeds (4751–6000)
 *   src/data/n3/vocabularyN3Seeds.ts      N3 course seeds (7001+)
 *   scripts/levels/playlistLessons.json   frozen lesson membership (this script keeps it)
 *
 * Outputs
 *   src/data/wordLevels.ts                id → level (listed vs assumed)   [generated]
 *   src/data/playlistLessons.ts           level lessons as id rows          [generated]
 *   scripts/levels/playlistLessons.json   frozen state, commit it
 *   docs/youtube-playlists.md             playlist plan with every video title
 *   scripts/levels/_level_report.txt      words whose level was assumed, conflicts
 *
 * Level rules, in order:
 *   1. ids in N1_VOCAB_IDS (the curated N1 set) are N1;
 *   2. otherwise the word's level on the list (easiest level if on several);
 *   3. otherwise assumed from the course: N2 for ids below 7001, N3 from 7001.
 *
 * Playlist lessons are FROZEN: once a lesson exists its ids never move, so
 * titles and numbers of published videos stay valid. New words become new
 * lessons appended to their level. Re-run after adding vocabulary.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");
const LEVELS = ["N5", "N4", "N3", "N2", "N1"];
const LESSON_SIZE = 10;
const MIN_TAIL = 5;

// ── read inputs ───────────────────────────────────────────────────────
const listLevel = new Map();
for (const line of readFileSync(join(here, "jlptWordLevels.tsv"), "utf8").split(/\r?\n/)) {
  if (!line || line.startsWith("#")) continue;
  const [word, , level] = line.split("|");
  if (LEVELS.includes(level)) listLevel.set(word, level);
}

/** Records are `{ id: …, word: … }` blocks; some batches are indented differently, so split on any indent. */
function parseSeeds(file, expectMin, expectExact) {
  const text = readFileSync(join(root, file), "utf8").replace(/\r\n/g, "\n");
  const out = [];
  for (const chunk of text.split(/\n[ \t]*\{[ \t]*\n(?=[ \t]*id:)/).slice(1)) {
    const id = /^\s*id:\s*(\d+),/.exec(chunk)?.[1];
    const word = /\n\s+word:\s*"([^"]+)"/.exec(chunk)?.[1];
    const sub = /\n\s+subcategory:\s*"([^"]+)"/.exec(chunk)?.[1] ?? "Mixed";
    if (id && word) out.push({ id: Number(id), word, sub });
  }
  if (out.length < expectMin || (expectExact && out.length !== expectExact)) {
    throw new Error(`${file}: parsed ${out.length} items, expected ${expectExact ?? `at least ${expectMin}`}`);
  }
  return out;
}

const vocabText = readFileSync(join(root, "src/data/vocabulary.ts"), "utf8");
const n1Block = /const N1_VOCAB_IDS = new Set<number>\(\[([\s\S]*?)\]\)/.exec(vocabText)?.[1] ?? "";
const N1_IDS = new Set((n1Block.match(/\d+/g) ?? []).map(Number));

const items = [
  ...parseSeeds("src/data/vocabulary.ts", 750, 750),
  ...parseSeeds("src/data/vocabularyCore2000Seeds.ts", 1250, 1250),
  ...parseSeeds("src/data/n3/vocabularyN3Seeds.ts", 50),
];
const seenId = new Set();
for (const it of items) {
  if (seenId.has(it.id)) throw new Error(`duplicate vocabulary id ${it.id}`);
  seenId.add(it.id);
}

// ── levels ────────────────────────────────────────────────────────────
const listed = Object.fromEntries(LEVELS.map((l) => [l, []]));
const assumed = { N2: [], N3: [] };
const conflicts = [];
const levelOf = new Map();
for (const it of items) {
  const fromList = listLevel.get(it.word);
  let level;
  if (N1_IDS.has(it.id)) {
    level = "N1";
    if (fromList && fromList !== "N1") conflicts.push(`${it.id} ${it.word}: curated N1, list says ${fromList}`);
    listed.N1.push(it.id);
  } else if (fromList) {
    level = fromList;
    listed[level].push(it.id);
  } else {
    level = it.id >= 7001 ? "N3" : "N2";
    assumed[level].push(it.id);
  }
  levelOf.set(it.id, level);
}

const rowsOf = (ids) => {
  const sorted = [...ids].sort((a, b) => a - b);
  const lines = [];
  for (let i = 0; i < sorted.length; i += 14) lines.push("    " + sorted.slice(i, i + 14).join(", ") + ",");
  return lines.join("\n");
};

const levelsTs = `// AUTO-GENERATED by scripts/levels/generateLevels.mjs — do not edit.
// Real JLPT level of every vocabulary item (N2 course, Core 2000, N3 course).
// LISTED: on the level list in scripts/levels/jlptWordLevels.tsv (or the curated N1 set).
// ASSUMED: not on any list, so the course level is used (N2 below id 7001, N3 from 7001).

import type { JlptLevel } from "../types/level";

export const LISTED_LEVEL_IDS: Readonly<Record<JlptLevel, readonly number[]>> = {
${LEVELS.map((l) => `  ${l}: [\n${rowsOf(listed[l])}\n  ],`).join("\n")}
};

export const ASSUMED_LEVEL_IDS: Readonly<Partial<Record<JlptLevel, readonly number[]>>> = {
  N2: [
${rowsOf(assumed.N2)}
  ],
  N3: [
${rowsOf(assumed.N3)}
  ],
};
`;
writeFileSync(join(root, "src/data/wordLevels.ts"), levelsTs, "utf8");

// ── frozen playlist lessons ───────────────────────────────────────────
const statePath = join(here, "playlistLessons.json");
const state = existsSync(statePath) ? JSON.parse(readFileSync(statePath, "utf8")) : {};
const byId = new Map(items.map((it) => [it.id, it]));

// Theme families give each lesson one clear topic, in teaching order.
const FAMILY_OF = new Map();
const FAMILY_ORDER = [];
for (const line of readFileSync(join(here, "themeFamilies.tsv"), "utf8").split(/\r?\n/)) {
  if (!line || line.startsWith("#")) continue;
  const [sub, family] = line.split("|");
  FAMILY_OF.set(sub, family);
  if (!FAMILY_ORDER.includes(family)) FAMILY_ORDER.push(family);
}
for (const it of items) {
  if (!FAMILY_OF.has(it.sub)) throw new Error(`subcategory "${it.sub}" (id ${it.id}) is not in themeFamilies.tsv`);
}

/** Split one family's words into lessons of ten; a short tail joins the last lesson (max 14). */
function chunkFamily(ids) {
  const chunks = [];
  for (let i = 0; i < ids.length; i += LESSON_SIZE) chunks.push(ids.slice(i, i + LESSON_SIZE));
  if (chunks.length > 1 && chunks[chunks.length - 1].length < MIN_TAIL) {
    const tail = chunks.pop();
    chunks[chunks.length - 1].push(...tail);
  }
  return chunks;
}

/** New lessons for words not yet in any lesson: one family at a time, small families pooled into a mix. */
function buildNewLessons(fresh) {
  const out = [];
  const pool = [];
  for (const family of FAMILY_ORDER) {
    const ids = fresh.filter((it) => FAMILY_OF.get(it.sub) === family).map((it) => it.id);
    if (ids.length === 0) continue;
    if (ids.length < MIN_TAIL) {
      pool.push(...ids.map((id) => ({ id, family })));
      continue;
    }
    const chunks = chunkFamily(ids);
    chunks.forEach((c, i) => out.push({ theme: chunks.length > 1 ? `${family} ${i + 1}` : family, ids: c }));
  }
  if (pool.length > 0 && pool.length < 3 && out.length > 0) {
    out[out.length - 1].ids.push(...pool.map((p) => p.id)); // one or two strays join the last lesson
  } else if (pool.length) {
    const chunks = chunkFamily(pool.map((p) => p.id));
    chunks.forEach((c, i) => {
      const fams = [...new Set(pool.filter((p) => c.includes(p.id)).map((p) => p.family))];
      const name = fams.length <= 2 ? fams.join(" + ") : `${fams.slice(0, 2).join(" + ")} + more`;
      const label = fams.length === 1 ? name : `Mixed Review: ${name}`;
      out.push({ theme: chunks.length > 1 ? `${label} ${i + 1}` : label, ids: c });
    });
  }
  return out;
}

for (const level of LEVELS) {
  const ids = items.filter((it) => levelOf.get(it.id) === level);
  const current = new Set(ids.map((it) => it.id));
  const lessons = (state[level] ?? []).map((l) => ({ theme: l.theme, ids: l.ids.filter((id) => current.has(id)) }));
  const assigned = new Set(lessons.flatMap((l) => l.ids));
  const fresh = ids.filter((it) => !assigned.has(it.id));
  lessons.push(...buildNewLessons(fresh));
  state[level] = lessons;
}
writeFileSync(statePath, JSON.stringify(state, null, 1) + "\n", "utf8");

// every id must sit in exactly one lesson
const placed = new Map();
for (const level of LEVELS) {
  for (const l of state[level]) for (const id of l.ids) {
    if (placed.has(id)) throw new Error(`id ${id} is in two playlist lessons`);
    placed.set(id, level);
    if (levelOf.get(id) !== level) throw new Error(`id ${id} is in the ${level} playlist but is ${levelOf.get(id)}`);
  }
}
for (const it of items) if (!placed.has(it.id)) throw new Error(`id ${it.id} is in no playlist lesson`);

const lessonId = (level, n) => `pl-${level.toLowerCase()}-${String(n).padStart(2, "0")}`;
const rowLines = [];
for (const level of LEVELS) {
  state[level].forEach((l, i) => {
    if (l.ids.length === 0) return;
    rowLines.push(`  [${JSON.stringify(lessonId(level, i + 1))}, ${JSON.stringify(level)}, ${JSON.stringify(l.theme)}, [${l.ids.join(", ")}]],`);
  });
}
const lessonsTs = `// AUTO-GENERATED by scripts/levels/generateLevels.mjs — do not edit.
// Level-pure vocabulary lessons for the YouTube playlists. Membership is frozen in
// scripts/levels/playlistLessons.json: existing lessons never change, new words
// become new lessons at the end of their level.

import type { PlaylistLessonRow } from "../types/level";

export const PLAYLIST_LESSON_ROWS: readonly PlaylistLessonRow[] = [
${rowLines.join("\n")}
];
`;
writeFileSync(join(root, "src/data/playlistLessons.ts"), lessonsTs, "utf8");

// ── docs + report ─────────────────────────────────────────────────────
const NAMES = {
  N5: ["N5 Beginner", "Absolute-beginner words: everyday actions, time, food and basic adjectives."],
  N4: ["N4 Elementary", "Elementary words for daily life, travel and simple conversation."],
  N3: ["N3 Intermediate", "Intermediate words for work, school, news and natural conversation."],
  N2: ["N2 Upper-Intermediate", "Upper-intermediate words for business, society and abstract topics."],
  N1: ["N1 Advanced", "Advanced words: formal, specialised and literary vocabulary."],
};
const count = (re) => (readFileSync(join(root, "src/data/grammar.ts"), "utf8").match(re) ?? []).length;
const n3Grammar = (readFileSync(join(root, "src/data/n3/grammarN3.ts"), "utf8").match(/\n\s+id:\s*9\d{3},/g) ?? []).length;
const gN2 = count(/courseLevel: "N2_(?:CORE|SECONDARY)"/g);
const gN1 = count(/courseLevel: "N1"/g);
const gN3 = count(/courseLevel: "N3_REVIEW"/g) + n3Grammar;
const doc = [];
doc.push("# YouTube playlists by level", "");
doc.push("Generated by `node scripts/levels/generateLevels.mjs` — do not edit by hand.", "");
doc.push("The channel is for English speakers learning Japanese at every level. Each level has a vocabulary playlist (below), and grammar playlists that already exist in the table of contents.", "");
doc.push("| Playlist | Vocabulary lessons | Words | Grammar playlist (TOC) |", "|---|---:|---:|---|");
const grammarWhere = {
  N5: "not written yet",
  N4: "not written yet (about 21 N4 patterns sit inside the N3 and N2 lessons)",
  N3: `Page 5 · N3 — ${gN3} patterns`,
  N2: `Page 1 — ${gN2} patterns`,
  N1: `Page 2 · N1 — ${gN1} patterns`,
};
for (const level of LEVELS) {
  const wc = state[level].reduce((s, l) => s + l.ids.length, 0);
  doc.push(`| ${NAMES[level][0]} | ${state[level].filter((l) => l.ids.length).length} | ${wc} | ${grammarWhere[level]} |`);
}
doc.push("", "Topic playlists that already exist: Onomatopoeia, Phone Conversations, Speech Styles, Synonyms & Antonyms, Konbini, Trip, Interview Prep.", "");
for (const level of LEVELS) {
  doc.push(`## ${NAMES[level][0]} — Vocabulary`, "", NAMES[level][1], "");
  state[level].forEach((l, i) => {
    if (l.ids.length === 0) return;
    doc.push(`${i + 1}. JLPT ${level} Vocabulary #${i + 1} | ${l.theme} (${l.ids.length} words)`);
  });
  doc.push("");
}
mkdirSync(join(root, "docs"), { recursive: true });
writeFileSync(join(root, "docs/youtube-playlists.md"), doc.join("\n"), "utf8");

const report = [];
report.push("Words whose level is ASSUMED (not on the level list) — review these:");
for (const [lvl, ids] of Object.entries(assumed)) {
  report.push(`${lvl} (${ids.length}): ` + ids.map((id) => `${id}${byId.get(id).word}`).join(" "));
}
report.push("", `Curated-N1 conflicts with the list (${conflicts.length}):`, ...conflicts);
writeFileSync(join(here, "_level_report.txt"), report.join("\n") + "\n", "utf8");

console.log(
  "levels:",
  LEVELS.map((l) => `${l} ${listed[l].length + (assumed[l]?.length ?? 0)}`).join(" · "),
  `| assumed ${assumed.N2.length + assumed.N3.length}`,
  `| lessons`,
  LEVELS.map((l) => `${l} ${state[l].filter((x) => x.ids.length).length}`).join(" · ")
);
