/**
 * Builds src/data/illustrations.ts from scripts/illustrations/*.tsv
 *
 *   node scripts/generateIllustrations.mjs
 *
 * Source format (pipe-delimited, one item per line, `#` lines are comments):
 *   id|word-or-pattern|picture|motion
 *
 * picture: one emoji (Unicode 13 or older so Windows 10 draws it), or
 *          svg:<id> for the hand-drawn animated set in
 *          src/components/Illustration/svgArt.tsx.
 *          Leave picture and motion empty for "no picture".
 * motion:  bob | float | wiggle | pulse | spin | shake | drift | bounce | rain
 *
 * The word/pattern column is kept in the output so the corpus test can
 * catch rows that went stale after a vocabulary or grammar edit.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const SOURCE_DIR = join(here, "illustrations");
const OUT = join(here, "..", "src", "data", "illustrations.ts");

const MOTIONS = new Set(["bob", "float", "wiggle", "pulse", "spin", "shake", "drift", "bounce", "rain"]);
/** Must match the keys of SVG_ART in src/components/Illustration/svgArt.tsx. */
const SVG_IDS = new Set([
  "washer",
  "fridge",
  "vacuum",
  "heater",
  "ventfan",
  "ricecooker",
  "pressurecooker",
  "appliances",
  "broken",
]);

function read(file) {
  const rows = [];
  const seen = new Set();
  const text = readFileSync(join(SOURCE_DIR, file), "utf8");
  for (const [i, raw] of text.split("\n").entries()) {
    const line = raw.replace(/\r$/, "");
    if (!line.trim() || line.startsWith("#")) continue;
    const parts = line.split("|");
    const where = `${file}:${i + 1}`;
    if (parts.length !== 4) throw new Error(`${where} expected 4 fields, got ${parts.length}`);
    const [idText, label, picture, motion] = parts.map((s) => s.trim());
    const id = Number(idText);
    if (!Number.isInteger(id) || id <= 0) throw new Error(`${where} bad id "${idText}"`);
    if (seen.has(id)) throw new Error(`${where} duplicate id ${id}`);
    seen.add(id);
    if (!label) throw new Error(`${where} missing word/pattern`);
    if (!picture !== !motion) {
      throw new Error(`${where} picture and motion must both be set or both be empty`);
    }
    if (motion && !MOTIONS.has(motion)) throw new Error(`${where} bad motion "${motion}"`);
    if (picture.startsWith("svg:") && !SVG_IDS.has(picture.slice(4))) {
      throw new Error(`${where} unknown svg "${picture}"`);
    }
    if (picture && !picture.startsWith("svg:") && [...picture].length > 8) {
      throw new Error(`${where} picture should be a single emoji`);
    }
    rows.push([id, label, picture || null, motion || null]);
  }
  return rows.sort((a, b) => a[0] - b[0]);
}

const vocab = read("vocabIllustrations.tsv");
const grammar = read("grammarIllustrations.tsv");

const line = ([id, label, picture, motion]) =>
  `  [${id}, ${JSON.stringify(label)}, ${JSON.stringify(picture)}, ${JSON.stringify(motion)}],`;

const out = `// AUTO-GENERATED by scripts/generateIllustrations.mjs — do not edit.
// Edit scripts/illustrations/*.tsv and re-run the script instead.

import type { PictureRow } from "../types/illustration";

/** Vocabulary pictures: [id, word, picture | null, motion | null]. */
export const VOCAB_PICTURE_ROWS: readonly PictureRow[] = [
${vocab.map(line).join("\n")}
];

/** Grammar pictures: [id, pattern, picture | null, motion | null]. */
export const GRAMMAR_PICTURE_ROWS: readonly PictureRow[] = [
${grammar.map(line).join("\n")}
];
`;

writeFileSync(OUT, out, "utf8");
const pictured = (rows) => rows.filter((r) => r[2]).length;
console.log(
  `illustrations: vocabulary ${pictured(vocab)}/${vocab.length} with pictures, grammar ${pictured(grammar)}/${grammar.length}`
);
