/**
 * Glossary generator + sanity check for the JLPT Trainer content data.
 *
 * Usage:  npm run glossary
 *
 * - Writes GLOSSARY.md listing every vocabulary word and grammar pattern,
 *   grouped by lesson, so new content can be checked against what exists.
 * - Fails (exit 1) when it finds duplicate words/patterns, duplicate ids,
 *   ids referenced by a lesson but missing from the data, or items that
 *   belong to no lesson.
 *
 * Re-run whenever a word or grammar pattern is added.
 */
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { vocabulary } from "../src/data/vocabulary";
import { lessons } from "../src/data/lessons";
import { grammar, grammarLessons } from "../src/data/grammar";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const problems: string[] = [];

function checkDuplicates(
  label: string,
  entries: { id: number; key: string }[]
): void {
  const byKey = new Map<string, number[]>();
  const byId = new Map<number, number>();
  for (const e of entries) {
    byKey.set(e.key, [...(byKey.get(e.key) ?? []), e.id]);
    byId.set(e.id, (byId.get(e.id) ?? 0) + 1);
  }
  for (const [key, ids] of byKey) {
    if (ids.length > 1) {
      problems.push(`Duplicate ${label} "${key}" (ids ${ids.join(", ")})`);
    }
  }
  for (const [id, count] of byId) {
    if (count > 1) problems.push(`Duplicate ${label} id ${id} (${count}x)`);
  }
}

checkDuplicates(
  "word",
  vocabulary.map((v) => ({ id: v.id, key: v.word }))
);
checkDuplicates(
  "grammar pattern",
  grammar.map((g) => ({ id: g.id, key: g.pattern }))
);

// Lesson coverage: every referenced id exists, every item is in a lesson
const vocabById = new Map(vocabulary.map((v) => [v.id, v]));
const grammarById = new Map(grammar.map((g) => [g.id, g]));
const usedVocabIds = new Set<number>();
const usedGrammarIds = new Set<number>();

for (const lesson of lessons) {
  for (const id of lesson.vocabularyIds) {
    if (!vocabById.has(id)) {
      problems.push(`Lesson ${lesson.id} references missing vocab id ${id}`);
    }
    if (usedVocabIds.has(id)) {
      problems.push(`Vocab id ${id} appears in more than one lesson`);
    }
    usedVocabIds.add(id);
  }
}
for (const lesson of grammarLessons) {
  for (const id of lesson.grammarIds) {
    if (!grammarById.has(id)) {
      problems.push(`Lesson ${lesson.id} references missing grammar id ${id}`);
    }
    if (usedGrammarIds.has(id)) {
      problems.push(`Grammar id ${id} appears in more than one lesson`);
    }
    usedGrammarIds.add(id);
  }
}
for (const v of vocabulary) {
  if (!usedVocabIds.has(v.id)) {
    problems.push(`Vocab id ${v.id} (${v.word}) is not in any lesson`);
  }
}
for (const g of grammar) {
  if (!usedGrammarIds.has(g.id)) {
    problems.push(`Grammar id ${g.id} (${g.pattern}) is not in any lesson`);
  }
}

// ── Build GLOSSARY.md ────────────────────────────────────────────────────────
const lines: string[] = [];
lines.push("# JLPT Trainer — Content Glossary");
lines.push("");
lines.push(
  "Auto-generated by `npm run glossary` — do not edit by hand. " +
    "Re-run after adding words or grammar patterns to refresh this list " +
    "and sanity-check for duplicates."
);
lines.push("");
lines.push(
  `**Totals:** ${vocabulary.length} vocabulary words · ` +
    `${grammar.length} grammar patterns · ` +
    `${lessons.length} word lessons · ${grammarLessons.length} grammar lessons`
);
lines.push("");

lines.push("## Vocabulary Words");
lines.push("");
for (const lesson of lessons) {
  lines.push(`### ${lesson.id} — ${lesson.title}`);
  lines.push("");
  lines.push("| ID | Word | Reading | Meaning |");
  lines.push("| --- | --- | --- | --- |");
  for (const id of lesson.vocabularyIds) {
    const v = vocabById.get(id);
    if (!v) continue;
    lines.push(`| ${v.id} | ${v.word} | ${v.reading} | ${v.meaning} |`);
  }
  lines.push("");
}

lines.push("## Grammar Patterns");
lines.push("");
for (const lesson of grammarLessons) {
  lines.push(`### ${lesson.id} — ${lesson.title}`);
  lines.push("");
  lines.push("| ID | Pattern | Meaning |");
  lines.push("| --- | --- | --- |");
  for (const id of lesson.grammarIds) {
    const g = grammarById.get(id);
    if (!g) continue;
    lines.push(`| ${g.id} | ${g.pattern} | ${g.meaning} |`);
  }
  lines.push("");
}

lines.push("## Quick duplicate-check lists");
lines.push("");
lines.push(
  "All words (one line, for a fast Ctrl+F before adding a new item):"
);
lines.push("");
lines.push("```");
lines.push(vocabulary.map((v) => v.word).join("、"));
lines.push("```");
lines.push("");
lines.push("All grammar patterns:");
lines.push("");
lines.push("```");
lines.push(grammar.map((g) => g.pattern).join("、"));
lines.push("```");
lines.push("");

writeFileSync(join(root, "GLOSSARY.md"), lines.join("\n"), "utf8");

if (problems.length > 0) {
  console.error(`GLOSSARY written, but ${problems.length} problem(s) found:`);
  for (const p of problems) console.error(`  - ${p}`);
  process.exit(1);
}
console.log(
  `GLOSSARY.md written: ${vocabulary.length} words, ${grammar.length} grammar patterns. No duplicates.`
);
