import type { Lesson } from "../types/lesson";
import type { JlptLevel } from "../types/level";
import { PLAYLIST_LESSON_ROWS } from "./playlistLessons";

/**
 * Level playlists: vocabulary lessons that contain only words of one real
 * JLPT level, for the YouTube playlists. Built from the frozen rows in
 * playlistLessons.ts (generated by scripts/levels/generateLevels.mjs), so
 * the existing N2 / N3 / N1 lessons and their titles are untouched.
 */

export const PLAYLIST_LEVEL_INFO: Readonly<Record<JlptLevel, { name: string; description: string }>> = {
  N5: { name: "N5 Beginner", description: "Absolute-beginner words" },
  N4: { name: "N4 Elementary", description: "Elementary words for daily life" },
  N3: { name: "N3 Intermediate", description: "Intermediate words for work and conversation" },
  N2: { name: "N2 Upper-Intermediate", description: "Upper-intermediate words for business and society" },
  N1: { name: "N1 Advanced", description: "Advanced, formal and specialised words" },
};

const ID_RE = /^pl-n([1-5])-(\d+)$/;

/** `pl-n5-03` for N5 lesson 3. */
export function formatPlaylistLessonId(level: JlptLevel, lessonNumber: number): string {
  return `pl-${level.toLowerCase()}-${String(lessonNumber).padStart(2, "0")}`;
}

export function parsePlaylistLessonId(id: string): { level: JlptLevel; number: number } | null {
  const m = ID_RE.exec(id);
  if (!m) return null;
  const number = Number(m[2]);
  return number >= 1 ? { level: `N${m[1]}` as JlptLevel, number } : null;
}

export const playlistLessons: Lesson[] = PLAYLIST_LESSON_ROWS.map(([id, level, theme, ids]) => {
  const parsed = parsePlaylistLessonId(id);
  const n = parsed?.number ?? 0;
  const title = `JLPT ${level} Vocabulary #${n} | ${theme}`;
  return {
    id,
    title,
    subtitle: theme,
    youtubeTitle: title,
    category: PLAYLIST_LEVEL_INFO[level].name,
    subcategories: [theme],
    vocabularyIds: [...ids],
  };
});

const BY_ID = new Map(playlistLessons.map((l) => [l.id, l]));

export function getPlaylistLessonById(id: string): Lesson | undefined {
  return BY_ID.get(id);
}

/** Lessons of one level, in order. */
export function playlistLessonsForLevel(level: JlptLevel): Lesson[] {
  const prefix = `pl-${level.toLowerCase()}-`;
  return playlistLessons.filter((l) => l.id.startsWith(prefix));
}

/**
 * Lesson number and running word range for a playlist lesson. Words are
 * numbered across the level (lesson 2 starts after lesson 1's last word),
 * and the last lesson of a level may hold fewer or a few more than ten.
 */
export function getPlaylistWordRange(
  lessonId: string
): { lessonNumber: number; firstWordNumber: number; lastWordNumber: number } | null {
  const parsed = parsePlaylistLessonId(lessonId);
  if (!parsed) return null;
  let first = 1;
  for (const lesson of playlistLessonsForLevel(parsed.level)) {
    const last = first + lesson.vocabularyIds.length - 1;
    if (lesson.id === lessonId) return { lessonNumber: parsed.number, firstWordNumber: first, lastWordNumber: last };
    first = last + 1;
  }
  return null;
}
